const assert=require('node:assert/strict');require('./shape-engine.js');const P=require('./parts-engine.js'),G=require('./stage-guide.js');
let count=0;
for(const shape of ['frog','fish','bunny','bear','heart','ball','butterfly','turtle','bird','leaf','fan','cone','pear','dome'])for(const detail of [2,3,4])for(const threadDiameter of [.2,.25]){
 const g=P.build(P.example(shape),{detail,threadDiameter});assert.ok(g.validation.valid);assert.equal(g.joins.length,g.components.length-1);assert.ok(g.maxPasses<=g.passLimit);
 const picked=g.stages.flatMap(st=>st.operations.filter(o=>o.kind==='pick').map(o=>o.id));assert.equal(picked.length,g.nodes.length);assert.equal(new Set(picked).size,g.nodes.length);
 for(const c of g.components){if(c.kind!=='strand'&&c.mesh.stitch!=='peyote'){assert.equal(c.mesh.v.length-c.mesh.edges.length+c.mesh.f.length,c.mesh.open?1:2,'Mesh topology must match an open panel or a closed surface.');const uses=new Map();for(const f of c.mesh.f)for(let i=0;i<f.length;i++){const k=[f[i],f[(i+1)%f.length]].sort((a,b)=>a-b).join(':');uses.set(k,(uses.get(k)||0)+1);}assert.ok([...uses.values()].every(n=>c.mesh.open?n===1||n===2:n===2));}
  const st=g.stages[c.stage];assert.equal(st.ids.length,c.ids.length);assert.equal(new Set(st.layout.nodes.filter(n=>n.component===c.id).map(n=>n.id)).size,c.ids.length);assert.ok(st.layout.pos.every(p=>Number.isFinite(p.x)&&Number.isFinite(p.y)));
 }
 for(const n of g.nodes){const passes=g.stages.flatMap(st=>st.operations).filter(o=>o.id===n.id).length;assert.equal(g.counts.get(n.id),passes);}
 for(const j of g.joins){assert.equal(j.ids.length,0);assert.ok(j.pairs.every(p=>g.byId.get(p.a).component===j.parent&&g.byId.get(p.b).component===j.component));assert.equal(new Set(j.pairs.flatMap(p=>[p.a,p.b])).size,j.pairs.length*2);}
 for(const c of g.components.filter(c=>c.allowedParentIds)){const parent=g.components.find(p=>p.id===c.parent);assert.ok(!/^(left |right )?(head|.*eye.*)$/i.test(parent.name),'limbs must attach to the body');for(const pair of g.joins.find(j=>j.component===c.id).pairs){assert.ok(c.allowedParentIds.includes(pair.a),'planner must preserve anatomical anchor constraints');assert.ok(g.byId.get(pair.a).p[1]<parent.world[1],'limb anchor must be below the body center');}}
 const all=g.stages.flatMap(s=>s.operations);assert.equal(all.filter(o=>o.newThread).length,g.threadSections);for(let i=1;i<all.length;i++)if(!all[i].newThread&&!all[i].bridge)assert.equal(all[i-1].to,all[i].from);assert.ok(g.threadLengths.every(x=>x.estimatedMeters>0));count++;
}
assert.equal(P.ball(false).edges.length,40);assert.equal(P.ball(true).edges.length,70);
const g=P.build(P.example('frog'));assert.equal(g.components.length,7);assert.equal(g.nodes.length,116);assert.equal(g.components.filter(c=>/black eye bead/.test(c.name)).length,2);assert.ok(g.threadSections>=1);assert.ok(g.nodes.length<=200);assert.ok(g.components.some(c=>c.mesh.stitch==='peyote'));for(const st of g.stages){const svg=G.diagram(g,st,g.colors,g.palette,{labels:st.kind==='join'});assert.deepEqual([...svg.matchAll(/data-stage-pass="([^"]+)"/g)].map(m=>m[1]),st.operations.map(o=>o.id));}
const fixtures=require('./test-subjects.json');for(const d of Object.values(fixtures)){const g=P.build(d);assert.ok(g.validation.valid);assert.ok(g.components.length>1);}
console.log(`${count} parts configurations passed: peyote shaping and hollow tube surfaces, complete inventory, connected thread routes, reserved join passages, explicit anchor pairs, exact diagram order, and animal/object scene inputs.`);

for(const big of [false,true]){const m=P.ball(big);assert.equal(m.stitch,'peyote');let active=m.rounds[0];for(const group of m.groups.filter(g=>g.stitches)){const picked=group.stitches.flatMap(s=>s.picks);assert.deepEqual(group.stitches.flatMap(s=>s.anchors),[...active.slice(1),active[0]]);assert.equal(group.sequence.at(-1),picked[0]);assert.equal(group.stepUp,picked[0]);assert.ok(group.stitches.every(s=>s.picks.length===1||s.picks.length===2));assert.ok(group.stitches.every(s=>s.anchors.length===1||s.anchors.length===2));if(group.phase==='increase')assert.ok(picked.length>active.length);if(group.phase==='decrease')assert.ok(picked.length<active.length);active=picked;}assert.equal(active.length,5);assert.deepEqual(m.groups.at(-1).sequence,[...active.slice(1),active[0]]);}

for(const kind of ['leaf','fan','cone']){const g=P.build(P.example(kind));assert.equal(g.components[0].kind,kind);assert.ok(g.nodes.length<=10);assert.equal(g.threadSections,1);assert.ok(g.stages[0].instruction.includes(kind==='cone'?'triangular':'four-bead'));}
const dome=P.build(P.example('dome'));assert.equal(dome.components[0].mesh.open,true);assert.ok(!dome.components[0].mesh.groups.some(g=>g.phase==='closure'));assert.ok(dome.stages[0].instruction.includes('Leave the last round open'));

{const g=P.build(P.example('frog'));let prev=null;for(const st of g.stages)for(const o of st.operations){if(prev&&!o.newThread){const a=g.byId.get(prev.id),b=g.byId.get(o.id);if(a.component!==b.component){const ca=g.components.find(c=>c.id===a.component),cb=g.components.find(c=>c.id===b.component);assert.ok(ca.parent===cb.id||cb.parent===ca.id,'No working thread may jump between sibling limbs.');}}prev=o;}for(const j of g.joins)for(const p of j.pairs)assert.ok(Math.hypot(...g.byId.get(p.a).p.map((x,i)=>x-g.byId.get(p.b).p[i]))<=3.8);}

{const d=P.example('frog'),g=P.build(d);assert.ok(!g.components.some(c=>/shin/.test(c.name)));assert.equal(g.components.filter(c=>/head|body/.test(c.name)).length,1);const custom={title:'limb style check',parts:[{name:'long leg',type:'capsule',role:'solid',center:[0,0,0],end:[0,-4,0],size:[.3,.3,.3],color:'#a9c8a0'},{name:'long neck',type:'capsule',role:'solid',center:[0,0,0],end:[0,4,0],size:[.3,.3,.3],color:'#a9c8a0'}]};const shaped=P.amigurumiScene(custom);assert.equal(shaped.parts[0].end[1],-2.4);assert.equal(shaped.parts[1].end[1],4);assert.equal(custom.parts[0].end[1],-4,'Style conversion must not mutate the saved reference.');}

{const g=P.build(P.example('frog')),stage=g.stages[g.components.find(c=>c.name==='head and body').stage],svg=G.diagram(g,stage,g.colors,g.palette);assert.equal((svg.match(/data-peyote-band=/g)||[]).length,9);assert.ok(svg.includes('data-ring-arc="true"'));assert.equal((svg.match(/data-stage-pass=/g)||[]).length,stage.operations.length);assert.ok(g.components.filter(c=>c.kind==='paw').every(c=>c.ids.length===4));const last=stage.operations.at(-1);assert.ok(svg.includes('data-stage-pass="'+last.id+'"'));}

{const g=P.build(P.example('frog')),eyes=g.nodes.filter(n=>n.diameterMm===4);assert.equal(eyes.length,2);assert.ok(eyes.every(n=>n.material==='4 mm black round eye bead'));assert.equal(g.materials.find(m=>m.name==='11/0 round seed bead').count,114);const st=g.stages[0],pause=st.operations.findIndex(o=>o.pauseBefore);assert.ok(pause>0);const firstDecrease=st.steps.find(s=>s.label.includes('decrease'));assert.equal(st.operations[pause].step,firstDecrease.index);assert.ok(pause<st.operations.length-5);}

{const g=P.build(P.example("frog"));assert.equal(g.threadSections,1);assert.ok(!g.components.some(c=>/haunch|paw/.test(c.name)));assert.equal(g.components.filter(c=>/leg/.test(c.name)&&c.kind==="strand"&&c.ids.length===4).length,2);for(const name of ["left leg","right thigh","left shin"]){const d=P.example("ball");d.parts.push({name,type:"ellipsoid",role:"solid",center:[1,0,0],end:[1,0,0],size:[.4,.4,.4],color:"#7caa80"});assert.equal(P.build(d).components.find(c=>c.name===name).kind,"strand");}}
