(function(root){
'use strict';
const distance=(a,b)=>Math.hypot(...a.map((v,i)=>v-b[i]));
function plan(g){
 const base=new Map(g.components.map(c=>[c.id,g.stages[c.stage]])),oldJoins=new Map(g.joins.map(j=>[j.component,j])),known=new Set(),counts=new Map(g.nodes.map(n=>[n.id,0])),future=new Map(g.nodes.map(n=>[n.id,g.faces.filter(f=>f.ids.includes(n.id)).length])),reserve=new Map(),adj=new Map(),bridges=new Map();
 for(const n of g.nodes){n.addedAt=-1;for(const v of n.ends){if(!adj.has(v))adj.set(v,[]);adj.get(v).push(n.id);}}
 for(const c of g.components)if(c.mesh.stitch==='peyote')for(const group of c.mesh.groups)for(const i of group.sequence){const id=c.ids[i];future.set(id,(future.get(id)||0)+1);}
 let cursor=null,section=0,last=null,steps=[],activeMoves=[],activeIds=[],reasons=[];
 g.steps=[];g.stages=[];g.joins=[];
 const room=(id,extra=new Map())=>g.passLimit-counts.get(id)-(future.get(id)||0)-(reserve.get(id)||0)-(extra.get(id)||0);
 function route(from,to,extra=new Map()){
  if(from===to)return [];if(from===null)return null;
  // Never chain two exposed connections: pass through a bead before another join.
  const start=from+'|0',q=[{v:from,cost:0,key:start,bridge:false,used:new Set()}],best=new Map([[start,0]]),prev=new Map();
  while(q.length){q.sort((a,b)=>a.cost-b.cost);const cur=q.shift();if(cur.cost!==best.get(cur.key))continue;if(cur.v===to){const out=[];let key=cur.key;while(key!==start){const hop=prev.get(key);out.unshift(hop);key=hop.previous;}return out;}
   const next=[];for(const id of adj.get(cur.v)||[]){if(!known.has(id)||cur.used.has(id)||room(id,extra)<1)continue;const n=g.byId.get(id);next.push({id,from:cur.v,to:n.ends[0]===cur.v?n.ends[1]:n.ends[0],cost:1,bridge:false});}if(!cur.bridge)for(const v of bridges.get(cur.v)||[])next.push({id:null,from:cur.v,to:v,cost:.05,bridge:true});
   for(const n of next){const cost=cur.cost+n.cost,key=n.to+'|'+Number(n.bridge);if(cost<(best.get(key)??Infinity)){best.set(key,cost);prev.set(key,{...n,previous:cur.key});q.push({v:n.to,cost,key,bridge:n.bridge,used:n.id?new Set([...cur.used,n.id]):cur.used});}}
  }return null;
 }
 function connect(a,b){if(!bridges.has(a))bridges.set(a,new Set());if(!bridges.has(b))bridges.set(b,new Set());bridges.get(a).add(b);bridges.get(b).add(a);}
 function fresh(v,reason){cursor=v;section++;last=null;if(reason)reasons.push({section,reason});}
 function pass(id,phase='weave',from=cursor){const n=g.byId.get(id);if(!n.ends.includes(from))throw Error('The continuous route missed a bead entrance.');const to=n.ends[0]===from?n.ends[1]:n.ends[0],kind=known.has(id)?'pass':'pick';if(counts.get(id)>=g.passLimit)throw Error('The continuous route exceeded its planned passage limit.');const o={id,kind,from,to,phase,section,newThread:last===null,bridge:last!==null&&last.to!==from};if(o.newThread&&section>1)o.restartReason=reasons.at(-1)?.reason;activeMoves.push(o);if(kind==='pick'){activeIds.push(id);n.addedAt=g.steps.length;}known.add(id);counts.set(id,counts.get(id)+1);cursor=to;last=o;return o;}
 function travel(path){for(const hop of path){if(hop.id)pass(hop.id,'position');else cursor=hop.to;}}
 function saveStep(label,component,faceId){if(!activeMoves.length)return;const st={index:g.steps.length,label,component,faceId,ids:activeIds,ops:activeMoves.map(o=>({kind:o.kind,id:o.id})),moves:activeMoves};g.steps.push(st);steps.push(st);activeMoves=[];activeIds=[];}
 function finishStage(template,instruction,layout){const operations=steps.flatMap(st=>st.moves.map((o,i)=>({...o,step:st.index,local:i,cube:template.component}))),ids=steps.flatMap(st=>st.ids),st={...template,index:g.stages.length,start:steps[0].index,end:steps.at(-1).index,steps,blocks:[{cubeId:template.component,steps}],ids,nodeIds:[...new Set(operations.map(o=>o.id))],operations,instruction};st.layout=contextLayout(g,st,layout);g.stages.push(st);steps=[];return st;}
 function chooseAttachment(parent,child,adjust=true){let best=null;for(const separate of [false,true]){for(const a of parent.ids){if(child.allowedParentIds&&!child.allowedParentIds.includes(a))continue;if(room(a)<(separate?2:3))continue;for(const side of [0,1]){const extra=new Map([[a,separate?2:3]]),entry=g.byId.get(a).ends[side],path=separate?null:route(cursor,entry,extra),restart=path===null;for(const b of child.ids){const n=g.byId.get(b);if(n.landmark&&child.mesh.stitch!=='peyote'&&child.kind!=='strand')continue;if((child.mesh.stitch==='peyote'||child.kind==='strand')&&b!==child.ids[0])continue;if(child.kind==='tube'&&!n.vertices.every(v=>v<5)&&!n.vertices.every(v=>v>=child.mesh.v.length-5))continue;if(distance(g.byId.get(a).p,n.p)>3.8)continue;const score=(restart?1000000:0)+(path?.filter(h=>h.id).length||0)*100+distance(g.byId.get(a).p,n.p)*1.5;if(!best||score<best.score)best={a,b,side,entry,path,restart,separate,score};}}}if(best)break;}if(!best&&adjust){
 // Tuck an unbuilt joint closer to an unused parent bead, preserving its subtree.
 const available=parent.ids.filter(id=>(!child.allowedParentIds||child.allowedParentIds.includes(id))&&room(id)>=2),entryIds=child.mesh.stitch==='peyote'||child.kind==='strand'?[child.ids[0]]:child.ids.filter(id=>{const n=g.byId.get(id);return child.kind!=='tube'||n.vertices.every(v=>v<5)||n.vertices.every(v=>v>=child.mesh.v.length-5);});
 const moves=[];for(const a of available)for(const b of entryIds){const pa=g.byId.get(a).p,pb=g.byId.get(b).p,d=distance(pa,pb),shift=pa.map((v,i)=>v+(pb[i]-v)*2.15/(d||1)-pb[i]);if(Math.hypot(...shift)>4)continue;const collision=[...known].some(id=>child.ids.some(cid=>distance(g.byId.get(id).p,g.byId.get(cid).p.map((v,i)=>v+shift[i]))<((g.byId.get(id).diameterMm||2)+(g.byId.get(cid).diameterMm||2))/2));if(!collision)moves.push({shift,d:Math.hypot(...shift)});}
 moves.sort((a,b)=>a.d-b.d);if(moves.length){const shift=moves[0].shift,subtree=new Set([child.id]);for(const c of g.components)if(subtree.has(c.parent))subtree.add(c.id);for(const c of g.components)if(subtree.has(c.id)){c.world=c.world.map((v,i)=>v+shift[i]);c.vertices=c.vertices.map(p=>p.map((v,i)=>v+shift[i]));for(const id of c.ids){const n=g.byId.get(id);n.p=n.p.map((v,i)=>v+shift[i]);}}return chooseAttachment(parent,child,false);}
 }if(!best)throw Error('No close attachment for '+child.name+' to '+parent.name+' fits the available hole space. Try 0.20 mm line or simplify this joint; the planner will not span the gap with loose thread.');return best;}

 function buildFaces(c,anchor){const pending=g.faces.filter(f=>f.id.startsWith(c.id+'F')).slice();let first=true;
  while(pending.length){let best=null;for(const f of pending){if(!first&&!f.ids.some(id=>known.has(id)))continue;if(first&&anchor&&(!f.ids.includes(anchor.b)||(c.kind==='tube'&&f.ids.length!==5)))continue;
   for(let offset=0;offset<f.corners.length;offset++)for(const rev of [false,true]){const cs=rev?f.corners.slice().reverse():f.corners,ordered=cs.map((_,i)=>cs[(i+offset)%cs.length]),ring=ordered.map((v,i)=>f.ids.find(id=>{const ends=g.byId.get(id).ends;return ends.includes(v)&&ends.includes(ordered[(i+1)%ordered.length]);}));if(first&&anchor&&(ring[0]!==anchor.b||ordered[0]!==anchor.childEntry))continue;if(!first&&!known.has(ring[0]))continue;
    const seq=[...ring,ring[0]],extra=new Map();seq.forEach(id=>extra.set(id,(extra.get(id)||0)+1));f.ids.forEach(id=>extra.set(id,extra.get(id)-1));if(seq.some(id=>room(id,extra)<0))continue;const path=route(cursor,ordered[0],extra),restart=path===null,score=(restart&&cursor!==null?1000000:0)+(path?.filter(h=>h.id).length||0)*3+seq.reduce((n,id)=>n+counts.get(id),0)-f.ids.filter(id=>known.has(id)).length;
    if(!best||score<best.score)best={f,seq,path,entry:ordered[0],restart,score};
   }}if(!best)throw Error('A loop cannot fit within the hole-space planning limit. Try a smaller ball or 0.20 mm line.');
   if(best.restart)fresh(best.entry,cursor===null?null:'No route through the existing beads remained within their passage budget.');else travel(best.path);
   for(const id of best.seq)pass(id);best.f.ids.forEach(id=>future.set(id,future.get(id)-1));saveStep(`close ${best.f.ids.length}-bead loop`,c.id,best.f.id);pending.splice(pending.indexOf(best.f),1);first=false;
  }
 }
 for(const c of g.components){let anchor=null,parent=null;const original=base.get(c.id);
  if(c.parent){parent=g.components.find(p=>p.id===c.parent);anchor=chooseAttachment(parent,c);if(c.kind==='strand')anchor.b=c.ids[0];const childNode=g.byId.get(anchor.b);anchor.childEntry=childNode.ends[0];anchor.childExit=childNode.ends[1];anchor.parentExit=g.byId.get(anchor.a).ends[1-anchor.side];reserve.set(anchor.a,2);reserve.set(anchor.b,2);
   if(anchor.separate){fresh(anchor.childEntry,'Starting this part separately avoids an extra passage through its parent anchor.');}else{if(anchor.restart)fresh(anchor.entry,'The next attachment could not be reached within the existing beads’ passage budget.');else travel(anchor.path);pass(anchor.a,'position');connect(cursor,anchor.childEntry);cursor=anchor.childEntry;saveStep('reach '+parent.name+' anchor '+anchor.a,c.id);}
  }
  if(c.mesh.stitch==='peyote'){
   for(const group of c.mesh.groups){for(const i of group.sequence){const id=c.ids[i],entry=g.byId.get(id).ends[0];if(cursor===null)fresh(entry,null);else if(cursor!==entry){connect(cursor,entry);cursor=entry;}future.set(id,future.get(id)-1);pass(id);}if(group.pauseBefore)activeMoves[0].pauseBefore=group.pauseBefore;saveStep(group.label,c.id);}
  }else if(c.kind==='strand'){
   if(cursor===null)fresh(g.byId.get(c.ids[0]).ends[0],null);for(const id of c.ids)pass(id);cursor=g.byId.get(c.ids.at(-1)).ends[0];for(const id of c.ids.slice(0,-1).reverse())pass(id);saveStep(c.mesh.eye?'pick up the 4 mm black eye bead':'string, skip the tip, and return',c.id);
  }else buildFaces(c,anchor);
  c.stage=g.stages.length;const instruction=(anchor?.separate?`Start this part with the marked new working length to save hole space at ${parent.name}. Join it in the next step. `:anchor?`Keep the working line attached to ${parent.name}. The positioning passes bring you to ${anchor.a}; continue into ${anchor.b} to start ${c.name}. `:'Start the project with a tail for finishing. ')+original.instruction.replace(/Start with the outer \d-bead loop\./,'Start with a '+(g.faces.find(f=>f.id===steps.find(s=>s.faceId)?.faceId)?.ids.length||5)+'-bead loop at the marked starting bead.')+' Do not cut or finish the working line here; continue to the next step.';
  finishStage(original,instruction,original.layout);
  if(anchor){
   // Close the initial connection as a two-anchor loop, then reinforce it.
   const needed=new Map([[anchor.b,2],[anchor.a,2]]);reserve.set(anchor.a,0);reserve.set(anchor.b,0);let path=route(cursor,anchor.childEntry,needed);
   if(path===null)fresh(anchor.childEntry,'Returning to the attachment would overfill an already-used bead.');else travel(path);
   pass(anchor.b);connect(cursor,anchor.entry);cursor=anchor.entry;pass(anchor.a);connect(cursor,anchor.childEntry);cursor=anchor.childEntry;pass(anchor.b);cursor=anchor.entry;pass(anchor.a);saveStep('close and reinforce the attachment',c.id);
   const pairs=[{a:anchor.a,b:anchor.b}],join=oldJoins.get(c.id);
   if(c.kind!=='strand'){
    let best=null;const candidates=[];for(const a of parent.ids)if((!c.allowedParentIds||c.allowedParentIds.includes(a))&&a!==anchor.a&&room(a)>=2)for(const b of c.ids)if(b!==anchor.b&&room(b)>=2&&distance(g.byId.get(a).p,g.byId.get(b).p)<=3.8)candidates.push({a,b,d:distance(g.byId.get(a).p,g.byId.get(b).p)});candidates.sort((a,b)=>a.d-b.d);
    for(const {a,b,d} of candidates){if(best&&d*1.5>=best.score)break;const extra=new Map([[a,2],[b,2]]),entry=g.byId.get(a).ends[0],path=route(cursor,entry,extra),score=(path===null?1000000:0)+(path?.filter(h=>h.id).length||0)*100+d*1.5;if(!best||score<best.score)best={a,b,path,entry,score};}
    if(best){if(best.path===null)fresh(best.entry,'The second attachment could not be reached without overfilling a bead.');else travel(best.path);const a=g.byId.get(best.a),b=g.byId.get(best.b);pass(a.id);connect(cursor,b.ends[0]);cursor=b.ends[0];pass(b.id);connect(cursor,a.ends[0]);cursor=a.ends[0];pass(a.id);cursor=b.ends[0];pass(b.id);saveStep('work the second attachment',c.id);pairs.push({a:a.id,b:b.id});}
   }
   const nodes=pairs.flatMap(p=>[g.byId.get(p.a),g.byId.get(p.b)]),layout={nodes,index:new Map(nodes.map((n,i)=>[n.id,i])),pos:nodes.map((n,i)=>({x:190+i%2*180,y:120+Math.floor(i/2)*120})),axes:nodes.map(()=>[0,1]),W:560,H:400};
   const st=finishStage({...join,pairs,caption:`No new beads · ${pairs.length} attachment loop${pairs.length===1?'':'s'} · keep the same working line`},`Return through the listed beads to ${anchor.b}, then cross into ${anchor.a} on ${parent.name}. Reinforce that connection with the working line. ${pairs.length===2?'Continue through the positioning beads to the second pair and work that attachment too. ':'Use this reinforced close joint as a flexible hinge; do not stretch a second loop across open space. '}Do not tie off between these steps. Green anchor outlines belong to ${parent.name}; rose outlines belong to ${c.name}.`,layout);g.joins.push(st);
  }
 }
 const final=g.stages.at(-1);final.instruction=final.instruction.replace(/Do not cut or finish the working line here; continue to the next step\./,'').replace(/Do not tie off between these steps\./,'')+' This is the final step: secure the working end and starting tail with your tested finish.';
 g.anchorIds=new Set(g.joins.flatMap(j=>j.pairs.flatMap(p=>[p.a,p.b])));g.counts=counts;g.maxPasses=Math.max(...counts.values());g.threadSections=section;g.threadChanges=reasons;g.continuous=true;let mm=0,prev=null;for(const st of g.stages)for(const o of st.operations){mm+=g.byId.get(o.id).diameterMm===4?4:1.3;if(prev&&prev.section===o.section)mm+=Math.max(0,distance(g.byId.get(prev.id).p,g.byId.get(o.id).p)-1.3);prev=o;}g.threadEstimateM=Math.ceil((mm*1.3+section*400)/100)/10;const lengths=new Map();let previous=null;for(const st of g.stages)for(const o of st.operations){if(!lengths.has(o.section))lengths.set(o.section,{number:o.section,mm:0,startStage:st.index+1});const item=lengths.get(o.section);item.mm+=g.byId.get(o.id).diameterMm===4?4:1.3;if(previous&&previous.section===o.section)item.mm+=Math.max(0,distance(g.byId.get(previous.id).p,g.byId.get(o.id).p)-1.3);previous=o;}g.threadLengths=[...lengths.values()].map(x=>({number:x.number,startStage:x.startStage,estimatedMeters:Math.ceil((x.mm*1.3+400)/100)/10}));
 g.notes=g.notes.filter(n=>!n.startsWith('Working thread:'));g.notes.push(`Working thread: ${section} planned length${section===1?'':'s'}. Estimated total ${g.threadEstimateM.toFixed(1)} m including 30% routing allowance and 40 cm of tails per length; this is not a measured cut length.`);
 g.validation=root.BeadParts.validate(g);if(!g.validation.valid)throw Error(g.validation.errors.join(' '));return g;
}
function contextLayout(g,stage,source){const nodes=source.nodes.slice(),pos=source.pos.map(p=>({...p})),axes=source.axes.map(a=>a.slice()),extra=stage.nodeIds.filter(id=>!source.index.has(id));for(let i=0;i<extra.length;i++){nodes.push(g.byId.get(extra[i]));pos.push({x:55+(i%10)*45,y:source.H+45+Math.floor(i/10)*48});axes.push([1,0]);}return {...source,nodes,pos,axes,index:new Map(nodes.map((n,i)=>[n.id,i])),W:source.W,H:source.H+(extra.length?100+Math.floor((extra.length-1)/10)*48:0)};}
root.BeadContinuous={plan};if(typeof module!=='undefined')module.exports=root.BeadContinuous;
})(typeof window!=='undefined'?window:globalThis);
