(() => {
'use strict';
const $=id=>document.getElementById(id),J=BeadJourney,U=Beadform.ui;
const photoOK=s=>typeof s==='string'&&s.length<=450000&&/^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/.test(s);
const failureModes=['loose structure','visible thread','uneven shaping','twisted tube','weak joint','hard to follow'];
function sanitize(b,keepConsent=true){if(!b||!photoOK(b.photo))return null;return {issues:Array.isArray(b.issues)?[...new Set(b.issues.filter(x=>failureModes.includes(x)))]:[],photo:b.photo,notes:typeof b.notes==='string'?b.notes.slice(0,1000):'',outcome:['worked','adjusted','unfinished'].includes(b.outcome)?b.outcome:'unfinished',useForInference:keepConsent&&b.useForInference===true,useForTraining:keepConsent&&b.useForTraining===true,added:typeof b.added==='string'?b.added:new Date().toISOString(),snapshot:b.snapshot&&typeof b.snapshot==='object'?b.snapshot:null};}
function snapshot(project){return {title:project.title,dimension:project.dimension,description:project.creation?.prompt||'',design:project.settings?.design||(project.dimension==='volume'&&project.settings?.shape&&project.settings.shape!=='custom'?BeadParts.example(project.settings.shape):null),shape:project.settings?.shape||null,threadDiameter:project.settings?.threadDiameter||.25,partsGuideVersion:project.partsGuide?.version||null};}
async function normalize(file){if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type)||file.size>20*1024*1024)throw Error('choose a png, jpg or webp under 20 mb.');const url=URL.createObjectURL(file);try{const im=await U.loadImage(url);if(im.naturalWidth*im.naturalHeight>60000000)throw Error('please use a smaller photo.');const scale=Math.min(1,720/Math.max(im.naturalWidth,im.naturalHeight)),cv=document.createElement('canvas');cv.width=Math.round(im.naturalWidth*scale);cv.height=Math.round(im.naturalHeight*scale);const ctx=cv.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,cv.width,cv.height);ctx.drawImage(im,0,0,cv.width,cv.height);let photo=cv.toDataURL('image/jpeg',.78);if(photo.length>450000)photo=cv.toDataURL('image/jpeg',.5);if(!photoOK(photo))throw Error('this photo is still too large. please choose a smaller image.');return photo;}finally{URL.revokeObjectURL(url);}}
function edit(id=J.activeId){if(id===J.activeId&&!J.save())return;const row=J.items.find(x=>x.id===id);if(!row){U.toast('make or open a project first.');return;}let draft=sanitize(row.build)||{photo:'',notes:'',outcome:'worked',useForInference:false,useForTraining:false,added:new Date().toISOString(),snapshot:snapshot(row.project)},token=0;
 U.modal('you made it!',`<p>add a photo of your finished beadwork, and tell us what worked.</p><img id="buildPhotoPreview" class="built-photo" alt="your finished beadwork" ${draft.photo?'src="'+draft.photo+'"':'hidden'}><label class="field">finished-object photo<input id="buildPhotoFile" type="file" accept="image/png,image/jpeg,image/webp"></label><label class="field">how did it go?<select id="buildOutcome"><option value="worked">worked as written</option><option value="adjusted">i made some changes</option><option value="unfinished">still working on it</option></select></label><details class="build-issues"><summary>anything to improve?</summary>${failureModes.map((x,i)=>`<label class="check-label"><input type="checkbox" id="buildIssue${i}" ${(draft.issues||[]).includes(x)?'checked':''}>${x}</label>`).join('')}</details><label class="field">notes + changes<textarea id="buildNotes" maxlength="1000" placeholder="the feet needed fewer beads, the body held its shape…">${U.esc(draft.notes)}</textarea></label><label class="check-label"><input id="buildInfer" type="checkbox"> use this photo + feedback as a reference for my future ai generations</label><p class="help-text">when relevant, this sends the photo, notes and project shape to your connected ai service.</p><label class="check-label"><input id="buildTrain" type="checkbox"> include my photo + feedback in training-data exports</label><p class="help-text">only include photos you have permission to use. exports stay with you until you share them. this does not train a model automatically.</p><p id="buildPhotoStatus" role="status"></p><button id="saveBuildPhoto" class="button primary">save photo + notes</button><button id="removeBuildPhoto" class="text-button">remove photo + permissions</button>`);
 $('buildOutcome').value=draft.outcome;$('buildInfer').checked=draft.useForInference;$('buildTrain').checked=draft.useForTraining;
 $('buildPhotoFile').onchange=async e=>{const request=++token;$('saveBuildPhoto').disabled=true;try{const photo=await normalize(e.target.files[0]);if(request!==token)return;draft={...draft,photo,snapshot:snapshot(row.project),added:new Date().toISOString()};$('buildPhotoPreview').src=photo;$('buildPhotoPreview').hidden=false;$('buildPhotoStatus').textContent='photo ready.';}catch(e){$('buildPhotoStatus').textContent=e.message;}finally{if(request===token)$('saveBuildPhoto').disabled=false;}};
 $('saveBuildPhoto').onclick=()=>{if(!draft.photo){$('buildPhotoStatus').textContent='add a finished-object photo first.';return;}const build=sanitize({...draft,issues:failureModes.filter((x,i)=>$('buildIssue'+i).checked),notes:$('buildNotes').value,outcome:$('buildOutcome').value,useForInference:$('buildInfer').checked,useForTraining:$('buildTrain').checked});if(J.updateBuild(id,build)){$('modal').close();U.toast('photo + notes saved.');}else $('buildPhotoStatus').textContent='could not save. browser storage may be full; your previous photo is unchanged.';};
 $('removeBuildPhoto').onclick=()=>{token++;if(J.updateBuild(id,null)){$('modal').close();U.toast('photo and permissions removed.');}};
}
function approved(){return J.items.map(row=>({row,b:sanitize(row.build)})).filter(x=>x.b);}
function references(prompt){const words=new Set((prompt.toLowerCase().match(/[a-z]{3,}/g)||[]).filter(x=>!['the','with','and','little','bead','beaded','make'].includes(x)));return approved().filter(({b})=>b.useForInference&&b.outcome!=='unfinished').map(x=>({...x,score:[...words].filter(w=>(x.row.title+' '+x.b.notes+' '+(x.b.snapshot?.description||'')).toLowerCase().includes(w)).length})).filter(x=>!words.size||x.score>0).sort((a,b)=>b.score-a.score).slice(0,2).map(({row,b})=>({consented:true,title:row.title.slice(0,70),imageData:b.photo,notes:b.notes,outcome:b.outcome,design:b.snapshot?.design||null}));}
function dataset(){return approved().filter(({b})=>b.useForTraining).map(({row,b})=>({format:'beadform-build-feedback',version:1,title:row.title,photo:b.photo,feedback:b.notes,issues:b.issues||[],outcome:b.outcome,projectAtUpload:b.snapshot,consent:{trainingExport:true,recordedAt:b.added}}));}
function exportData(){const rows=dataset();if(!rows.length){U.toast('no photos are approved for training exports yet. add permission in a project’s build photo.');return;}const url=URL.createObjectURL(new Blob([rows.map(x=>JSON.stringify(x)).join('\n')],{type:'application/x-ndjson'})),a=document.createElement('a');a.href=url;a.download='beadform-approved-builds.jsonl';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);U.toast(rows.length+' approved build records exported.');}
$('finishedPhotoButton').onclick=()=>edit();$('exportBuildData').onclick=exportData;
window.BeadFinished={edit,sanitize,references,dataset,normalize};
})();
