(() => {
'use strict';
const $=id=>document.getElementById(id),T=Beadform3D,C=BeadCreator,U=Beadform.ui,key='beadform.projects.v1';
let items=[],active=null,screen='welcome',timer=null,opening=null,storageOK=true,dimension='volume',activeBuild=null;
try{const raw=localStorage.getItem(key);if(raw){const data=JSON.parse(raw);if(!Array.isArray(data)||data.some(x=>!x.id||!x.project))throw Error();items=data;}}catch(e){storageOK=false;}
function notice(message){$('projectSaveStatus').textContent=message;$('galleryNotice').textContent=message;}
function persist(next){if(!storageOK){notice('Browser storage is unavailable. Use Export to download your project.');return false;}try{localStorage.setItem(key,JSON.stringify(next));items=next;return true;}catch(e){notice('Could not save: browser storage may be full. Download your project before leaving.');return false;}}
function show(next){screen=next;for(const name of ['welcome','gallery','project'])document.body.classList.toggle('journey-'+name,next===name);$('projectGallery').hidden=next!=='gallery';$('projectToolbar').hidden=next!=='project';if(next!=='gallery')T.setMode(next==='welcome'?'volume':dimension);if(next==='project'){$('galleryProjectName').value=dimension==='flat'?$('projectTitle').value:T.state.title;if(dimension==='volume')$('pModelView').click();}const target=next==='gallery'?$('galleryTitle'):next==='welcome'?$('welcomeTitle'):$('galleryProjectName');target?.focus?.();}
function save(){clearTimeout(timer);if(!active||!BeadPartsStudio.model)return true;const b=Beadform.state;if(dimension==='flat'&&!b.geometry){notice('The flat preview is still loading. Try Save project in a moment.');return false;}const project=dimension==='flat'?{format:'beadform-project',version:1,dimension:'flat',title:$('projectTitle').value,sourceName:b.sourceName,sourceData:b.sourceData,settings:b.settings,palette:b.palette,colors:b.colors,step:b.step,manualEdits:b.edits}:T.project();const svg=dimension==='flat'?Beadform.exportSVG():T.state.construction==='lattice'?T.modelSVG():BeadPartsStudio.modelSVG();project.finishedBuild=activeBuild;const row={build:activeBuild,id:active,title:project.title,updated:Date.now(),thumbnail:'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg),project};const next=[row,...items.filter(x=>x.id!==active)];if(!persist(next))return false;notice('Saved in this browser');return true;}
function scheduleSave(){if(active&&screen==='project'){clearTimeout(timer);timer=setTimeout(save,800);}}
function created(){activeBuild=null;dimension='volume';document.body.classList.remove('pattern-arrived');requestAnimationFrame(()=>document.body.classList.add('pattern-arrived'));active='p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);show('project');save();}
function opened(nextDimension='volume',project={}){if(!opening)activeBuild=window.BeadFinished?.sanitize(project.finishedBuild,false)||null;dimension=nextDimension;active=opening||'p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);opening=null;show('project');save();}
function gallery(){if(screen==='project'&&!save())return;C.cancel(false);C.inputMode('text');show('gallery');renderGallery();}
function renderGallery(){const grid=$('galleryGrid');grid.innerHTML=items.length?items.map(x=>`<article class="project-tile"><button class="project-open" data-project-open="${U.esc(x.id)}"><img src="${U.esc(window.BeadFinished?.sanitize(x.build)?.photo||(/^data:image\/svg\+xml;charset=utf-8,/.test(x.thumbnail||'')?x.thumbnail:''))}" alt=""><strong>${U.esc(x.title)}</strong><small>${new Date(x.updated).toLocaleDateString()} · ${x.project.dimension==='flat'?'Flat pattern':'3D beadwork'}</small></button><div class="project-actions"><button class="text-button" data-project-rename="${U.esc(x.id)}">Rename</button><button class="text-button" data-project-download="${U.esc(x.id)}">Download</button><button class="text-button" data-project-photo="${U.esc(x.id)}">${x.build?'build photo':'add photo'}</button><button class="text-button" data-project-delete="${U.esc(x.id)}">Delete</button></div></article>`).join(''):'<div class="gallery-empty"><span class="empty-beads">● ● ●</span><h2>nothing here yet!</h2><p>start with an idea, a picture, or one of the animals.</p></div>';
 document.querySelectorAll('[data-project-photo]').forEach(b=>b.onclick=()=>window.BeadFinished?.edit(b.dataset.projectPhoto));document.querySelectorAll('[data-project-open]').forEach(b=>b.onclick=()=>open(b.dataset.projectOpen));document.querySelectorAll('[data-project-rename]').forEach(b=>b.onclick=()=>rename(b.dataset.projectRename));document.querySelectorAll('[data-project-delete]').forEach(b=>b.onclick=()=>remove(b.dataset.projectDelete));document.querySelectorAll('[data-project-download]').forEach(b=>b.onclick=()=>download(b.dataset.projectDownload));}
async function open(id){const row=items.find(x=>x.id===id);if(!row)return;opening=id;activeBuild=row.build||row.project.finishedBuild||null;T.state.edits=false;const data=JSON.stringify(row.project);try{if(row.project.dimension==='flat'){Beadform.state.edits=false;await Beadform.importProject({size:data.length,text:async()=>data});}else await T.importProject({size:data.length,text:async()=>data});}catch(e){notice('Could not open this project. Download a backup and try again.');}finally{opening=null;}}
function rename(id){const row=items.find(x=>x.id===id);if(!row)return;U.modal('Rename project',`<label class="field">Name<input id="renameProjectInput" maxlength="70" value="${U.esc(row.title)}"></label><button id="confirmRenameProject" class="button primary">Save name</button>`);$('confirmRenameProject').onclick=()=>{const title=$('renameProjectInput').value.trim();if(!title)return;const next=items.map(x=>x.id===id?{...x,title,project:{...x.project,title}}:x);if(persist(next)){if(active===id){if(dimension==='flat')$('projectTitle').value=title;else T.state.title=title;}$('modal').close();renderGallery();}};}
function remove(id){const row=items.find(x=>x.id===id);if(!row)return;U.modal('Delete this project?',`<p>Delete “${U.esc(row.title)}” from this browser? Download a backup first if you want to keep it.</p><button id="cancelDeleteProject" class="button secondary">Keep it</button><button id="confirmDeleteProject" class="button primary">Delete project</button>`);$('cancelDeleteProject').onclick=()=>$('modal').close();$('confirmDeleteProject').onclick=()=>{if(persist(items.filter(x=>x.id!==id))){if(active===id)active=null;$('modal').close();renderGallery();}};}
function download(id){const row=items.find(x=>x.id===id);if(!row)return;const url=URL.createObjectURL(new Blob([JSON.stringify(row.project)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=row.title.replace(/[^a-z0-9-]/gi,'_')+'.beadform-3d.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function fresh(){if(active&&!save())return;C.projectOpened({creation:{inputMode:'text'}});active=null;activeBuild=null;T.state.edits=false;T.state.source=null;T.state.sourceData='';T.state.sourceName='';T.state.sourceCustom=true;T.state.construction='parts';$('vPrompt').value='';$('referencePreview').hidden=true;$('vMaskTools').hidden=true;$('vGenerationStatus').textContent='';$('resumeProject').hidden=true;show('welcome');C.inputMode('text');}
function animal(name){if(!['frog','bunny','bear','fish','butterfly','turtle','bird'].includes(name))return;if(active&&!save())return;T.state.edits=false;T.state.construction='parts';const d=BeadParts.example(name);C.applyDesign(d,d.title,'Animal ready');}
$('galleryButton').onclick=gallery;$('newProjectButton').onclick=fresh;$('galleryNew').onclick=fresh;$('saveToGallery').onclick=save;$('editIdea').onclick=()=>{save();$('resumeProject').hidden=false;show('welcome');};$('resumeProject').onclick=()=>show('project');$('galleryProjectName').onchange=()=>{const title=$('galleryProjectName').value.trim()||'My beaded project';if(dimension==='flat')$('projectTitle').value=title;else{T.state.title=title;$('vTitle').value=title;BeadPartsStudio.refresh();}save();};
for(const [id,mode]of [['modeFlat','flat'],['modeVolume','volume']])$(id).onclick=()=>{if(dimension===mode)return;if(active&&!save())return;dimension=mode;activeBuild=null;active='p-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8);show('project');save();};
window.addEventListener('pagehide',()=>{if(active)save();});document.addEventListener('change',scheduleSave);document.addEventListener('click',scheduleSave);document.addEventListener('pointerup',scheduleSave);
window.BeadJourney={created,opened,animal,gallery,fresh,save,scheduleSave,open,rename,remove,get activeId(){return active;},getBuild(){return activeBuild;},updateBuild(id,build){const next=items.map(x=>x.id===id?{...x,build,project:{...x.project,finishedBuild:build}}:x);if(!persist(next))return false;if(active===id)activeBuild=build;if(screen==='gallery')renderGallery();return true;},get items(){return items;},get screen(){return screen;}};
show('welcome');if(!storageOK)notice('Browser storage is unavailable. Download project files to keep your work.');
})();
