(() => {
'use strict';
const T=window.Beadform3D,P=window.BeadParts,D=window.BeadStages,U=window.Beadform.ui,$=id=>document.getElementById(id),readable=v=>String(v).replace(/\bB0*(\d+)\b/g,(_,n)=>'bead '+Number(n)),esc=v=>U.esc(readable(v)),s=T.state;
let g=null,signature='',view='model',yaw=0,pitch=0,zoom=1,fullSignature='';
s.construction=s.construction||'parts';s.partsStage=s.partsStage||0;s.partsReveal=s.partsReveal??Infinity;
const countOps=()=>g?g.stages[s.partsStage].operations.length:0;
function current(){return g?.stages[Math.max(0,Math.min(g.stages.length-1,s.partsStage))];}
function design(){if(s.settings.shape==='custom'){if(s.settings.design.kind==='image')throw Error('To identify shaped beadwork parts in a picture, choose “interpret as a full 3D subject.” Upload your reference and choose “make from this picture” to create the full subject.');return s.settings.design;}return P.example(s.settings.shape);}
function refresh(){const active=s.construction==='parts';$('volumeStudio').classList.toggle('parts-mode',active);$('partsWorkspace').hidden=!active;$('vDepth').disabled=active;$('pBallSize').value=s.settings.detail===4?'4':'3';if(!active||!s.model)return;
 try{const d=design(),key=JSON.stringify([d,s.settings.detail,s.settings.threadDiameter]);if(key!==signature){g=P.build(d,s.settings);signature=key;view='model';yaw=0;pitch=0;zoom=1;s.partsStage=Math.max(0,Math.min(s.partsStage,g.stages.length-1));}g.title=s.title;$('pExport').disabled=false;render();}catch(e){g=null;signature='';$('pStatus').textContent=e.message;$('pCanvas').innerHTML='';$('pThreadPlan').innerHTML='';$('pStageList').innerHTML='';$('pInventory').innerHTML='';$('pShaping').innerHTML='';$('pFullPattern').innerHTML='';fullSignature='';$('pStepTitle').textContent='choose a simpler construction';$('pStepHint').textContent='';$('pActionNotice').hidden=true;$('pInstruction').textContent='Try fewer separate details, or describe the main body and limbs more clearly.';$('pAdded').textContent='';$('pExport').disabled=true;}
}
function silhouette(points){const pts=points.slice().sort((a,b)=>a.x-b.x||a.y-b.y),cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);const chain=a=>{const h=[];for(const p of a){while(h.length>1&&cross(h.at(-2),h.at(-1),p)<=0)h.pop();h.push(p);}return h;};const lo=chain(pts),hi=chain(pts.slice().reverse());return lo.slice(0,-1).concat(hi.slice(0,-1)).map(p=>p.x+','+p.y).join(' ');}
function rotatePoint(p){const a=yaw*Math.PI/180,t=pitch*Math.PI/180,x=p[0]*Math.cos(a)-p[2]*Math.sin(a),z=p[0]*Math.sin(a)+p[2]*Math.cos(a);return [x,p[1]*Math.cos(t)-z*Math.sin(t),p[1]*Math.sin(t)+z*Math.cos(t)];}
function projectPoint(p,W,H,bounds){const q=rotatePoint(p);return {x:W/2+(q[0]-bounds.cx)*bounds.scale,y:H/2-(q[1]-bounds.cy)*bounds.scale,z:q[2]};}
function modelSVG({width=900,height=530,simple=false,highlight=false,built=false,stageIndex=s.partsStage}={}){
 const centers=[0,1,2].map(i=>(Math.max(...g.nodes.map(n=>n.p[i]))+Math.min(...g.nodes.map(n=>n.p[i])))/2),center=rotatePoint(centers),diameter=2*Math.max(...g.nodes.map(n=>Math.hypot(...n.p.map((v,i)=>v-centers[i]))+(n.diameterMm||2)/2)),b={cx:center[0],cy:center[1],scale:Math.min((width-80)/diameter,(height-85)/diameter)*(width===900?zoom:1)},project=p=>projectPoint(p,width,height,b),st=g.stages[stageIndex],hi=new Set(highlight?st.nodeIds:[]),added=new Set(g.stages.slice(0,stageIndex).flatMap(st=>st.ids));st.operations.slice(0,stageIndex===s.partsStage?s.partsReveal:Infinity).filter(o=>o.kind==='pick').forEach(o=>added.add(o.id));
 let out=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(g.title)} assembled from shaped beadwork parts"><rect width="${width}" height="${height}" rx="12" fill="#fffdf9"/><defs><radialGradient id="parts-shine" cx="30%" cy="25%"><stop stop-color="#fff" stop-opacity=".7"/><stop offset="1" stop-color="#fff" stop-opacity="0"/></radialGradient></defs>`;
 for(const join of g.joins)for(const pair of join.pairs){const a=project(g.byId.get(pair.a).p),b=project(g.byId.get(pair.b).p);out+=`<path d="M${a.x} ${a.y} L${b.x} ${b.y}" stroke="#ad7591" stroke-width="1.2" stroke-dasharray="3 3"/>`;}
 if(simple){for(const c of g.components.slice().sort((a,b)=>project(a.world).z-project(b.world).z)){const p=project(c.world),r=c.mesh.radius*b.scale;
 out+=`<g data-part-stage="${c.stage}"><title>${esc(c.name)} · ${c.kind} · ${c.ids.length} beads</title>`;
 if(c.mesh.eye)out+=`<circle cx="${p.x}" cy="${p.y}" r="${r}" fill="#171c16"/>`;
 else if(c.kind==='ball')out+=`<circle cx="${p.x}" cy="${p.y}" r="${r*.88}" fill="${c.source.color}" stroke="#53785c" stroke-width="1.8"/><ellipse cx="${p.x}" cy="${p.y}" rx="${r*.87}" ry="${r*.26}" fill="none" stroke="#fff" stroke-opacity=".5"/>`;
 else if(['leaf','fan','cone','paw','sheet','pear','dome'].includes(c.kind))out+=`<polygon points="${silhouette(c.vertices.map(project))}" fill="${c.source.color}" stroke="#53785c" stroke-width="1.8"/>`;
 else{const ends=c.kind==='tube'?[c.vertices.slice(0,5),c.vertices.slice(-5)]:[[c.vertices[0]],[c.vertices.at(-1)]],centers=ends.map(v=>project(v.reduce((n,p)=>n.map((x,i)=>x+p[i]/v.length),[0,0,0])));out+=`<path d="M${centers[0].x} ${centers[0].y} L${centers[1].x} ${centers[1].y}" fill="none" stroke="${c.source.color}" stroke-width="${b.scale*(c.kind==='tube'?4.5:1.6)}" stroke-linecap="round" ${c.kind==='strand'?'stroke-dasharray="2 4"':''}/>`;}
 out+=`<circle cx="${p.x}" cy="${p.y}" r="12" fill="#fffdf9" stroke="#719279"/><text x="${p.x}" y="${p.y+4}" font-family="Arial" font-size="11" text-anchor="middle" fill="#416444">${c.stage+1}</text></g>`;}
 }else{
 const links=new Set();let prev=null;for(const step of g.stages)for(const o of step.operations){if(prev&&!o.newThread&&(!built||(added.has(prev.id)&&added.has(o.id)))){const key=[prev.id,o.id].sort().join(':');if(prev.id!==o.id&&!links.has(key)){links.add(key);const a=project(g.byId.get(prev.id).p),b=project(g.byId.get(o.id).p);out+=`<path d="M${a.x} ${a.y} L${b.x} ${b.y}" stroke="#688d77" stroke-width=".8" opacity=".48"/>`;}}prev=o;}
 for(const n of g.nodes.map(n=>({n,...project(n.p)})).sort((a,b)=>a.z-b.z)){if(built&&!added.has(n.n.id))continue;const c=g.palette[g.colors[n.n.index]],r=b.scale*(n.n.diameterMm||2)*.49,opacity=highlight&&!hi.has(n.n.id)?.16:1;out+=`<g data-pbead="${n.n.id}" opacity="${opacity}"><title>${readable(n.n.id)} · ${esc(g.components.find(c=>c.id===n.n.component).name)}</title><circle cx="${n.x}" cy="${n.y}" r="${r}" fill="${c}" stroke="#37543d80" stroke-width=".65"/><circle cx="${n.x}" cy="${n.y}" r="${r}" fill="url(#parts-shine)"/><ellipse cx="${n.x}" cy="${n.y}" rx="${r*.24}" ry="${r*.12}" fill="#29463270"/></g>`;}}
 out+=`<text x="22" y="${height-17}" font-family="Arial" font-size="12" fill="#907084">${simple?'shape symbols · select a part to make it':'shaped beadwork · fine lines show thread; dashed lines are joins'}</text></svg>`;return out;
}
function mapSVG(){const rows=Math.ceil(g.components.length/3),H=660+rows*115+g.joins.length*29;let out=`<svg xmlns="http://www.w3.org/2000/svg" width="1000" height="${H}" viewBox="0 0 1000 ${H}" role="img" aria-label="Parts and assembly map"><rect width="1000" height="${H}" fill="#fffdf9"/><text x="25" y="38" font-family="Georgia" font-size="28" fill="#416444">${esc(g.title)} · the parts map</text><text x="25" y="64" font-family="Arial" font-size="14" fill="#947187">${g.components.length} simple parts · ${g.nodes.length} beads · ${g.joins.length} joins</text>${modelSVG({width:950,height:465,simple:true}).replace('<svg ', '<svg x="25" y="85" ')}<text x="25" y="585" font-family="Arial" font-size="16" fill="#416444">Build the parts in order, keeping the line attached</text>`;
 for(let i=0;i<g.components.length;i++){const c=g.components[i],x=25+i%3*320,y=602+Math.floor(i/3)*115;out+=`<g data-part-stage="${c.stage}" role="button" tabindex="0" aria-label="Make ${esc(c.name)}"><rect x="${x}" y="${y}" width="300" height="94" rx="10" fill="#f2e7ec" stroke="#ddc7d1"/><text x="${x+14}" y="${y+27}" font-family="Arial" font-size="${Math.min(17,260/((c.name.length+4)*.55))}" fill="#416444">${c.id} · ${esc(c.name)}</text><text x="${x+14}" y="${y+53}" font-family="Arial" font-size="13" fill="#956b83">${c.mesh.eye?'4 mm black eye bead':c.kind==='ball'?'peyote ball':['pear','dome'].includes(c.kind)?'peyote '+c.kind:c.kind==='tube'?'short tube':c.kind==='strand'?'flexible strand':c.kind+' · angle weave'} · ${c.ids.length} beads</text><text x="${x+14}" y="${y+76}" font-family="Arial" font-size="11" fill="#708466">open the complete part guide ↗</text></g>`;}
 let y=rows*115+617;out+=`<text x="25" y="${y}" font-family="Arial" font-size="16" fill="#416444">Work these connections as each part is built</text>`;for(const j of g.joins){y+=29;out+=`<text x="35" y="${y}" font-family="Arial" font-size="13" fill="#907087">${j.component} → ${j.parent}: ${esc(j.label)} · ${j.pairs.length} attachment loop${j.pairs.length===1?'':'s'}</text>`;}return out+'</svg>';
}
function threadSVG(st=current(),full=false){return D.diagram(g,st,g.colors,g.palette,{width:950,reveal:full?Infinity:s.partsReveal,labels:$('pIds').checked||st.kind==='join',prefix:'parts'});}
function shaping(st){const c=g.components.find(c=>c.id===st.component);if(st.kind==='join'||c?.mesh.stitch!=='peyote')return '';const rows=c.mesh.groups.map((group,i)=>`${group.pauseBefore?`<tr><td colspan="3"><b>Optional filling pause</b> — ${esc(group.pauseBefore)}</td></tr>`:''}<tr><td>${i===0?'Start':group.phase==='closure'?'Close':'Round '+(i+1)}</td><td>${group.phase==='foundation'?'String five; pass through the first':group.phase==='closure'?'Pass the last five up-beads; draw snug':group.phase==='increase'?'Two beads at marked increases; step up':group.phase==='decrease'?'One bead, pass paired up-beads; step up':'One bead per gap; step up'}</td><td>${group.phase==='closure'?'0':c.mesh.rounds[i].length}</td></tr>`).join('');return `<details><summary>Peyote shaping recipe · open counts + step-ups</summary><p>The complete part stays in one chart. Use the exact pickup/pass sequence to locate each increase and decrease. A step-up passes through the first bead added in that round.</p><table><thead><tr><th>Section</th><th>Action</th><th>New beads</th></tr></thead><tbody>${rows}</tbody></table></details>`;}
function placementSVG(st=null){
 // Fixed front view keeps the assembly landmarks consistent throughout the sheet.
 const oldYaw=yaw,oldPitch=pitch;yaw=0;pitch=0;
 const W=620,H=450,centers=[0,1,2].map(i=>(Math.max(...g.nodes.map(n=>n.p[i]))+Math.min(...g.nodes.map(n=>n.p[i])))/2),diameter=2*Math.max(...g.nodes.map(n=>Math.hypot(...n.p.map((v,i)=>v-centers[i]))+(n.diameterMm||2)/2)),bounds={cx:centers[0],cy:centers[1],scale:Math.min((W-80)/diameter,(H-85)/diameter)},project=p=>projectPoint(p,W,H,bounds);
 let svg=modelSVG({width:W,height:H,highlight:!!st,stageIndex:st?.index||0}).replaceAll('parts-shine','context-shine-'+(st?.index??'overview'));
 const parts=st?[g.components.find(c=>c.id===st.component)]:g.components;
 let labels='';const sorted=parts.slice().sort((a,b)=>a.world[1]-b.world[1]);
 sorted.forEach((c,i)=>{const p=project(c.world),left=p.x<W/2,x=left?20:W-160,y=st?45:35+i*(H-85)/Math.max(1,parts.length-1),number=c.stage+1;
 labels+=`<g data-locate-stage="${c.stage}" tabindex="0" role="button" aria-label="go to ${esc(c.name)}"><path d="M${left?x+140:x} ${y+15} L${p.x} ${p.y}" fill="none" stroke="#b4537d" stroke-width="1.8"/><circle cx="${p.x}" cy="${p.y}" r="6" fill="#f4c6da" stroke="#244b37"/><rect x="${x}" y="${y}" width="140" height="30" rx="15" fill="#f4c6da"/><text x="${x+10}" y="${y+20}" font-family="Arial" font-size="12" fill="#244b37">${number}. ${esc(c.name)}</text></g>`;
 });
 if(st?.kind==='join')for(const pair of st.pairs){const a=project(g.byId.get(pair.a).p),b=project(g.byId.get(pair.b).p);for(const [p,id,color]of [[a,pair.a,'#244b37'],[b,pair.b,'#b4537d']])labels+=`<circle cx="${p.x}" cy="${p.y}" r="10" fill="none" stroke="${color}" stroke-width="2.5"/><text x="${p.x+12}" y="${p.y-10}" font-family="Arial" font-size="12" fill="${color}">${id}</text>`;}
 yaw=oldYaw;pitch=oldPitch;return svg.replace('</svg>',labels+'</svg>');
}
function togetherLayout(st){
 const owners=new Set([st.component,...st.operations.map(o=>g.byId.get(o.id).component)]);if(st.parent)owners.add(st.parent);
 const components=g.components.filter(c=>owners.has(c.id)),nodes=[],pos=[],axes=[];
 components.forEach((c,k)=>{const source=g.stages[c.stage].layout,scale=Math.min(480/source.W,420/source.H),x=(k%2)*520,y=Math.floor(k/2)*470;for(const id of c.ids){const n=g.byId.get(id),i=source.index.get(id);nodes.push(n);pos.push({x:x+20+source.pos[i].x*scale,y:y+35+source.pos[i].y*scale});axes.push(source.axes[i]);}});
 return {nodes,pos,axes,index:new Map(nodes.map((n,i)=>[n.id,i])),W:components.length>1?1040:520,H:Math.ceil(components.length/2)*470,components};
}
function togetherDiagram(st,options={}){const layout=togetherLayout(st);let svg=D.diagram(g,{...st,layout},g.colors,g.palette,{width:950,labels:$('pIds').checked,...options});const names=layout.components.map((c,i)=>`<text x="${i%2*520+25}" y="${Math.floor(i/2)*470+86}" font-family="Arial" font-size="16" fill="#244b37">${esc(c.name)}</text>`).join('');return svg.replace('</svg>',names+'</svg>');}
function attachmentCloseups(st){
 if(st.kind!=='join')return '';
 const parent=g.components.find(c=>c.id===st.parent),child=g.components.find(c=>c.id===st.component);
 return `<section class="attachment-closeup"><h4>attach here · close-up</h4><p>bring the marked beads together. use their holes, not the gap between them.</p>${st.pairs.map((pair,pairIndex)=>{
 const nodes=[g.byId.get(pair.a),g.byId.get(pair.b)],ops=st.operations.filter(o=>o.phase!=='position'&&(o.id===pair.a||o.id===pair.b)),layout={nodes,index:new Map(nodes.map((n,i)=>[n.id,i])),pos:[{x:110,y:95},{x:290,y:95}],axes:[[0,1],[0,1]],W:400,H:190};
 return `<div class="attachment-pair"><p><b>${st.pairs.length>1?'connection '+(pairIndex+1)+' · ':''}${esc(parent.name)} ↔ ${esc(child.name)}</b></p><div class="attachment-actions">${ops.map((op,i)=>{const destination=op.id===pair.a?parent.name:child.name,direction=op.from===g.byId.get(op.id).ends[0]?'top → bottom':'bottom → top',mini={...st,label:'pass '+(i+1),caption:destination+' · '+direction,ids:[],operations:ops.slice(0,i+1),layout};let svg=D.diagram(g,mini,g.colors,g.palette,{width:420,labels:$('pIds').checked,reveal:i+1,quiet:true,prefix:'attach-'+st.index+'-'+pairIndex+'-'+i});svg=svg.replace('</svg>',`<text x="110" y="110" text-anchor="middle" font-family="Arial" font-size="12" fill="#387b79">existing part</text><text x="290" y="110" text-anchor="middle" font-family="Arial" font-size="12" fill="#b74472">new part</text></svg>`);return `<figure data-attachment-pass="${op.id}">${svg}<figcaption>${op.newThread?'start the marked new length. ':''}${i===0?'enter':i===ops.length-1?'return through':'cross to'} ${esc(destination)}.</figcaption></figure>`;}).join('')}</div></div>`;
 }).join('')}<p class="attachment-finish">draw the loop snug so the beads sit together. keep the thread attached.</p><small>enlarged, flattened view · the gap is only to show the thread</small></section>`;
}
function shortInstruction(st){const c=g.components.find(c=>c.id===st.component);if(st.kind==='join')return 'follow the close-up passes, then pull snug.';if(c.mesh.eye)return 'add one 4 mm black eye bead. attach it in the next step.';if(c.kind==='strand')return `string ${c.ids.length} beads. skip the tip; pass back through the others.`;if(c.mesh.stitch==='peyote')return 'follow the shaded rounds. step up at each round end. fill before decreasing, if wanted.';return 'follow the numbered loops. reuse pale beads; add pink-outlined beads.';}
function repositioning(st){
 const runs=[];for(let i=0;i<st.operations.length;){if(st.operations[i].phase!=='position'){i++;continue;}const start=i;while(i<st.operations.length&&st.operations[i].phase==='position'&&(i===start||!st.operations[i].newThread))i++;runs.push({start,end:i,ops:st.operations.slice(start,i)});}
 if(!runs.length)return '';
 return '<div class="repositioning">'+runs.map((r,k)=>{const previous=r.start?st.operations[r.start-1]:g.stages[st.index-1]?.operations.at(-1),next=st.operations[r.end],fresh=r.ops[0].newThread,from=fresh?'start a new length':previous?'exit '+readable(previous.id):'start here',route=r.ops.map(o=>Number(o.id.slice(1))).join(' → '),mini={...st,label:'move the thread',caption:'green arrows · pass through existing beads · add none',ids:[],operations:r.ops};return `<section class="thread-transfer" data-transfer-stage="${st.index}"><h4>${r.start===0?'first: reposition':'after move '+r.start+': reposition'}</h4><p>follow the green thread. no new beads.</p><details><summary>bead numbers</summary><p>${esc(from)}</p><p class="thread-route">${esc(route)}</p></details>${togetherDiagram(mini,{prefix:'transfer-'+st.index+'-'+k})}<p class="thread-next">${next?`${next.kind==='pick'?'then add the highlighted bead':'continue through the highlighted bead'}.`:'keep this thread attached.'}</p></section>`;}).join('')+'</div>';
}
function fullPattern(){
 const key=signature+'|'+$('pIds').checked;
 if(fullSignature===key)return;fullSignature=key;
 $('pFullPattern').innerHTML=`<header class="full-pattern-heading"><span class="eyebrow">one pattern · start to finish</span><h2>make it, piece by piece.</h2><p>numbers on the animal match the steps below. keep the same thread until a new length is marked.</p><div class="assembly-overview">${placementSVG()}<div><h3>where everything goes</h3>${g.components.map(c=>`<button class="assembly-link" data-locate-stage="${c.stage}"><b>${c.stage+1}</b> ${esc(c.name)} <span>↗</span></button>`).join('')}</div></div></header><p class="visual-key"><span>● green dot: thread starts here</span><span>→ arrow: through the hole</span><span>◌ pink ring: next bead</span></p><div class="pattern-flow">`+g.stages.map((st,i)=>{
 const part=g.components.find(c=>c.id===st.component),parent=g.components.find(c=>c.id===(st.parent||part.parent));
 const connection=parent?`${part.name} → ${parent.name}`:'start with the main body';
 const chart=st.kind==='join'?togetherDiagram(st,{prefix:'full-'+i,quiet:true}):D.diagram(g,st,g.colors,g.palette,{width:950,reveal:Infinity,labels:$('pIds').checked,prefix:'full-'+i,quiet:true});
 const anchors=st.kind==='join'?st.pairs.map(p=>`${readable(p.a)} on ${parent.name} ↔ ${readable(p.b)} on ${part.name}`).join(' · '):'';
 const notices=st.operations.filter(o=>o.newThread&&o.section>1).map(o=>'start thread length '+o.section+' at '+o.id).join(' · ');
 return `<article id="full-stage-${i}" class="full-pattern-step" data-full-stage="${i}"><header><span class="pattern-number">${i+1}</span><div><h3>${esc(st.label)}</h3><p>${esc(connection)}</p></div></header><div class="full-step-layout"><aside class="full-step-context">${placementSVG(st)}<p class="placement-label">${st.kind==='join'?'green = body anchor · pink = new part':'pink pointer = the part you are making'}</p>${anchors?`<details class="anchor-pairs"><summary>attachment numbers</summary><p>${esc(anchors)}</p></details>`:''}<p>${esc(shortInstruction(st))}</p><details><summary>more detail</summary><p>${esc(st.instruction)}</p></details>${notices?`<p class="parts-progress">${esc(notices)}</p>`:''}${shaping(st)}</aside><div class="full-step-chart">${repositioning(st)}${attachmentCloseups(st)}<div id="inline-chart-${i}">${chart}</div><div class="inline-replay"><button class="text-button" data-full-replay="${i}">↶ replay</button><input id="inline-range-${i}" data-inline-range="${i}" type="range" min="0" max="${st.operations.length}" value="${st.operations.length}" aria-label="thread progress for step ${i+1}"><button class="text-button" data-inline-back="${i}">← before</button><button class="text-button" data-inline-next="${i}">after this move →</button><button class="text-button" data-inline-finish="${i}">show all</button><output id="inline-count-${i}" aria-live="polite">${st.ids.length} beads · overview</output><p id="inline-action-${i}" class="next-action">start at the green dot. follow the arrow into the pink ring.</p><p id="inline-notice-${i}" role="status"></p></div></div></div>${i<g.stages.length-1?`<div class="continue-thread">↓ ${g.stages[i+1].kind==='join'?'attach this part next':'continue to '+esc(g.stages[i+1].label)}</div>`:''}</article>`;
 }).join('')+'</div>';
 document.querySelectorAll('[data-full-replay]').forEach(b=>b.onclick=()=>inlineReveal(+b.dataset.fullReplay,0));
 document.querySelectorAll('[data-inline-range]').forEach(b=>b.oninput=()=>inlineReveal(+b.dataset.inlineRange,+b.value));
 document.querySelectorAll('[data-inline-back]').forEach(b=>b.onclick=()=>inlineReveal(+b.dataset.inlineBack,+$('inline-range-'+b.dataset.inlineBack).value-1));
 document.querySelectorAll('[data-inline-next]').forEach(b=>b.onclick=()=>inlineReveal(+b.dataset.inlineNext,+$('inline-range-'+b.dataset.inlineNext).value+1));
 document.querySelectorAll('[data-inline-finish]').forEach(b=>b.onclick=()=>inlineReveal(+b.dataset.inlineFinish,Infinity));
 document.querySelectorAll('[data-locate-stage]').forEach(b=>{const go=()=>$('full-stage-'+b.dataset.locateStage)?.scrollIntoView?.({behavior:'smooth',block:'start'});b.onclick=go;b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go();}};});
}
function inlineReveal(i,n){const st=g.stages[i],count=Math.max(0,Math.min(st.operations.length,n));$('inline-chart-'+i).innerHTML=st.kind==='join'?togetherDiagram(st,{reveal:count,prefix:'full-'+i,quiet:true}):D.diagram(g,st,g.colors,g.palette,{width:950,reveal:count,labels:$('pIds').checked,prefix:'full-'+i,quiet:true});$('inline-range-'+i).value=count;const next=st.operations[count];$('inline-action-'+i).textContent=next?`${next.newThread?'start a new length. ':''}next: ${next.kind==='pick'?'add the pink-ringed bead':'pass through the pink-ringed bead'}${next.phase==='position'?' · reposition':''}.`:'step complete. continue below.';const added=st.operations.slice(0,count).filter(o=>o.kind==='pick').length;$('inline-count-'+i).textContent=`${added} / ${st.ids.length} beads added · ${count} / ${st.operations.length} thread moves`;$('inline-notice-'+i).textContent=st.operations[count]?.pauseBefore||st.operations[count-1]?.pauseBefore||'';s.partsStage=i;s.partsReveal=count;window.BeadJourney?.scheduleSave();}
function drawPreview(){if(!g)return;const canvas=$('pCanvas');canvas.classList.toggle('is-model',view==='model');canvas.innerHTML=view==='plan'?mapSVG():view==='thread'?threadSVG():modelSVG({highlight:$('pBuilt').checked,built:$('pBuilt').checked});$('pZoomLabel').textContent=Math.round(zoom*100)+'%';}
function render(){if(!g)return;window.BeadJourney?.scheduleSave();s.partsStage=Math.max(0,Math.min(g.stages.length-1,s.partsStage));const st=current(),shown=Math.min(st.operations.length,s.partsReveal),newBeads=st.operations.slice(0,shown).filter(o=>o.kind==='pick').length;
 fullPattern();$('pStatus').textContent=`${g.nodes.length} beads · ${g.components.length} parts${g.nodes.length>200?' · above the 150–200 bead target':''}`;
 $('pThreadPlan').innerHTML=`<b>${g.threadSections===1?'One working line':g.threadSections+' working lengths'}</b> · ${g.threadLengths.reduce((n,x)=>n+x.estimatedMeters,0).toFixed(1)} m estimated<details><summary>Thread details</summary>Return through body beads between limbs. Required thread changes are marked in each step.<br>${g.threadLengths.map(x=>`Length ${x.number}: ${x.estimatedMeters.toFixed(1)} m`).join(' · ')}. Includes 30% routing allowance and 40 cm of tails per length.</details>`;
 $('pStageList').innerHTML=g.stages.map((st,i)=>`<button data-pstage="${i}" class="${i===s.partsStage?'active':''}">${st.kind==='join'?'↳':st.component} · ${esc(st.label)}<small>${st.kind==='join'?st.pairs.length+' attachment loops':st.ids.length+' beads · '+st.kind}</small></button>`).join('');document.querySelectorAll('[data-pstage]').forEach(b=>b.onclick=()=>select(+b.dataset.pstage));
 drawPreview();for(const [id,v]of [['pPlanView','plan'],['pModelView','model'],['pThreadView','thread']]){$(id).classList.toggle('active',view===v);$(id).setAttribute('aria-pressed',view===v);}
 const counts=g.palette.map(()=>0);g.colors.forEach(c=>counts[c]++);$('pInventory').innerHTML=`<span><b>${g.nodes.length}</b> physical beads</span>${g.materials.map(m=>`<span>${m.count} × ${esc(m.name)}</span>`).join('')}`+counts.map((n,i)=>`<span><i class="mini-bead" style="background:${g.palette[i]}"></i>${'color '+(i+1)} · ${n}</span>`).join('');
 $('pStepHint').textContent=st.kind==='join'?'Attach at the marked beads, keeping the joint snug.':g.components.find(c=>c.id===st.component)?.mesh.stitch==='peyote'?(g.components.find(c=>c.id===st.component)?.mesh.open?'Follow the shaded rounds; leave the rim open.':'Follow the shaded rounds. Optional filling goes in before decreasing.'):st.instruction.split('. ')[0]+'.';const action=st.operations[shown]?.pauseBefore||st.operations[shown-1]?.pauseBefore;const changes=st.operations.filter(o=>o.newThread&&o.section>1);$('pActionNotice').textContent=[action,...changes.map(o=>'Start thread length '+o.section+' at '+o.id+'.')].filter(Boolean).join(' ');$('pActionNotice').hidden=!$('pActionNotice').textContent;
 $('pShaping').innerHTML=shaping(st);$('pStepTitle').textContent=`${s.partsStage+1}. ${st.label}`;$('pStepCount').textContent=`${s.partsStage+1} / ${g.stages.length}`;$('pInstruction').textContent=st.instruction+st.operations.filter(o=>o.newThread&&o.section>1).map(o=>' Start length '+o.section+' here: '+o.restartReason).join('');if(st.operations[shown]?.pauseBefore||st.operations[shown-1]?.pauseBefore)$('pInstruction').textContent=(st.operations[shown]?.pauseBefore||st.operations[shown-1]?.pauseBefore)+' '+$('pInstruction').textContent;$('pAdded').textContent=st.kind==='join'?`No new beads in this step.`:`${newBeads} / ${st.ids.length} beads added`;$('pPrev').disabled=s.partsStage===0;$('pNext').disabled=s.partsStage===g.stages.length-1;$('pReveal').max=st.operations.length;$('pReveal').value=shown;$('pMoveCount').value=`${shown} / ${st.operations.length}`;$('pNextMove').disabled=shown>=st.operations.length;window.BeadMaker?.mount();
}
function select(i){if(!g)return;s.partsStage=Math.max(0,Math.min(g.stages.length-1,i));s.partsReveal=Infinity;view='thread';render();$('pCanvas').scrollTop=0;}
function reveal(n){if(!g)return;s.partsReveal=Math.max(0,Math.min(countOps(),n));if(view==='plan')view='thread';render();}
function exact(){if(!g)return;const st=current();U.modal(st.label+' · thread sequence',`<p class="modal-copy">PICK adds a bead. PASS reuses one. A fresh line starts at each ★. Keep the working line between parts. A ★ after length 1 marks a necessary change; otherwise continue without cutting.</p><div class="parts-moves">${st.operations.map((o,i)=>`<button data-pmove="${i}">${i+1}. ${o.pauseBefore?'FILLING PAUSE · ':''}${o.newThread?'★ length '+o.section+' · ':''}<b>${o.kind.toUpperCase()}</b> ${readable(o.id)}${g.byId.get(o.id).diameterMm===4?' · 4 mm eye bead':''} · ${o.phase==='position'?'move into position':esc(g.steps[o.step]?.label||g.components.find(c=>c.id===g.byId.get(o.id).component).name)}</button>`).join('')}</div>`);document.querySelectorAll('[data-pmove]').forEach(b=>b.onclick=()=>{reveal(+b.dataset.pmove+1);$('modal').close();});}
function textGuide(){const cc=g.palette.map(()=>0);g.colors.forEach(i=>cc[i]++);return readable([g.title+' — PARTS-FIRST BEAD GUIDE','11/0 seed beads; larger eye beads listed separately · '+s.settings.threadDiameter+' mm fishing line',`${g.nodes.length} beads · ${g.components.length} parts · ${g.joins.length} joins`,g.notes.join(' '),...g.materials.map(m=>m.count+' × '+m.name),'Optional: clean soft plastic film or lightweight craft filling. Add before the first decrease, not after closing.','Maximum planned passes: '+g.maxPasses+'. Starting, knots, tails, and finishing need additional hole space. Make a physical sample.',...g.palette.map((c,i)=>`color ${i+1} ${c}: ${cc[i]} beads; ${Math.ceil(cc[i]*1.1)} with spare.`),...g.stages.flatMap(st=>['',`${st.index+1}. ${st.label.toUpperCase()}`,st.instruction,st.caption,...st.operations.map((o,i)=>`${o.pauseBefore?o.pauseBefore+'\n':''}${i+1}. ${o.newThread?'START LENGTH '+o.section+'. '+(o.restartReason||'Keep this working line attached.')+' ':''}${o.kind.toUpperCase()} ${readable(o.id)} [color ${g.colors[g.byId.get(o.id).index]+1}]${o.phase==='position'?' — positioning':' — '+g.steps[o.step].label}`),st.index===g.stages.length-1?'Secure the working end and starting tail with your tested finish.':'Continue with the working line. Do not cut here.'])].join('\n'));}
function printGuide(){if(!g)return;const cc=g.palette.map(()=>0);g.colors.forEach(i=>cc[i]++);$('printArea').innerHTML=`<section class="print-cover"><h1>${esc(g.title)}</h1><p>Parts-first beadwork · ${g.nodes.length} total beads · 11/0 seed beads plus larger eyes where listed · ${s.settings.threadDiameter} mm fishing line</p>${modelSVG({width:900,height:560,simple:false})}<h2>Build + attach ${g.components.length} parts with ${g.threadSections} working length${g.threadSections===1?'':'s'}</h2><p>${esc(g.components.map(c=>`${c.id} ${c.name}: ${c.kind}, ${c.ids.length} beads`).join(' · '))}</p><p>Shape symbols are approximations; bead counts come from the thread charts. Shaped circular peyote makes the rounded parts, with increases, decreases and round-end step-ups. Tube walls use four-bead angle-weave loops. Strands remain flexible.</p></section><section class="print-legend"><h2>Thread plan + materials</h2>${g.materials.map(m=>`<p>${m.count} × ${esc(m.name)}</p>`).join('')}<p>Optional filling: clean, dry, soft plastic film or lightweight craft filling. Insert lightly before the first decrease. Keep the working rim and bead holes clear.</p><p>${g.threadSections===1?'Use one continuous working line; finish only at the end.':'Keep the line attached until an explicit new-length marker.'} Estimated preparation: ${g.threadLengths.map(x=>`length ${x.number}: ${x.estimatedMeters.toFixed(1)} m (starts at step ${x.startStage})`).join('; ')}. Includes 30% route allowance and 40 cm of tails per length; actual use varies.</p>${g.palette.map((c,i)=>`<p><span style="color:${c}">●</span> color ${i+1} ${c}: ${cc[i]} beads; prepare ${Math.ceil(cc[i]*1.1)} with 10% spare.</p>`).join('')}<p>Rose: weaving. Green: repositioning. Pale beads: already made. IDs always identify the same physical bead. Nested ball/tube maps show a whole surface opened into one diagram; each chart groups a complete part; peyote rounds are followed in the exact sequence. Follow the numbered movement list or saved-project replay for the exact order. A star marks the start of a working length. Continue the same line at all other stage boundaries; do not finish each part separately.</p><p>The join cards identify parent and child anchors. Build each new part from its parent anchor, then close and reinforce that attachment before starting the next part. Use two attachment loops where listed. Starting, finishing and knots are additional to the ${g.maxPasses} maximum planned passes. Test hole fit, access, tension, rigidity, and shape with your actual 11/0 beads and line. These plans have not been physically sampled.</p>${g.notes.map(n=>`<p>${esc(n)}</p>`).join('')}</section>`+g.stages.map(st=>`<section class="parts-print-step"><h2>${st.index+1}. ${esc(st.label)}</h2><p>${esc(st.instruction)}</p>${threadSVG(st,true)}${shaping(st).replace('<details>','<details open>')}<p>${esc(st.caption)}</p></section>`).join('');$('modal').close();setTimeout(()=>window.print(),150);}
function exports(){if(!g){U.toast('Choose a parts example or interpret the reference first.');return;}U.modal('your simpler pattern.',`<p class="modal-copy">${g.components.length} hollow or flexible parts, built and attached in order with ${g.threadSections} planned working length${g.threadSections===1?'':'s'}. These exports use the parts inventory.</p><div class="export-grid"><button id="pOutPrint" class="export-option"><b>complete pattern / PDF</b></button><button id="pOutMap" class="export-option"><b>parts map · SVG</b></button><button id="pOutThread" class="export-option"><b>this thread chart · SVG</b></button><button id="pOutText" class="export-option"><b>exact sequence · TXT</b></button><button id="pOutProject" class="export-option"><b>editable project · JSON</b></button><button id="pOutCsv" class="export-option"><b>beads + materials · CSV</b></button></div>`);$('pOutPrint').onclick=printGuide;$('pOutMap').onclick=()=>T.download(mapSVG(),'image/svg+xml','-parts-map.svg');$('pOutThread').onclick=()=>T.download(threadSVG(current(),true),'image/svg+xml','-part-thread.svg');$('pOutText').onclick=()=>T.download(textGuide(),'text/plain','-parts-guide.txt');$('pOutProject').onclick=()=>T.download(JSON.stringify(T.project()),'application/json','.beadform-3d.json');$('pOutCsv').onclick=()=>T.download('Bead,Part,Symbol,Hex,Planned passages,Material,Diameter mm\r\n'+g.nodes.map(n=>[n.id,n.component,String.fromCharCode(65+g.colors[n.index]),g.palette[g.colors[n.index]],g.counts.get(n.id),n.material,n.diameterMm].join(',')).join('\r\n'),'text/csv','-parts-beads.csv');}
$('pLoadExample').onclick=()=>{const name=$('pExample').value;if(!name)return;try{const d=P.example(name);P.build(d,s.settings);window.BeadCreator.applyDesign(d,d.title,'original shaped-parts example');}catch(e){U.toast(e.message);}};
$('pBallSize').onchange=()=>{$('vDetail').value=$('pBallSize').value;$('vDetail').onchange();};
$('pPlanView').onclick=()=>{view='plan';render();};$('pModelView').onclick=()=>{view='model';render();};$('pThreadView').onclick=()=>{$('pFullPattern').scrollIntoView?.({behavior:'smooth',block:'start'});};$('pTurnLeft').onclick=()=>{view='model';yaw-=30;render();};$('pTurnRight').onclick=()=>{view='model';yaw+=30;render();};$('pIds').onchange=render;$('pBuilt').onchange=()=>{view='model';render();};$('pPrev').onclick=()=>select(s.partsStage-1);$('pNext').onclick=()=>select(s.partsStage+1);$('pReplay').onclick=()=>reveal(0);$('pNextMove').onclick=()=>reveal(Math.min(countOps(),s.partsReveal)+1);$('pFinish').onclick=()=>reveal(countOps());$('pReveal').oninput=()=>reveal(+$('pReveal').value);$('pExact').onclick=exact;$('pExport').onclick=exports;$('pCanvas').addEventListener('click',e=>{const card=e.target.closest('[data-part-stage]');if(card)select(+card.dataset.partStage);});$('pCanvas').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){const card=e.target.closest('[data-part-stage]');if(card){e.preventDefault();select(+card.dataset.partStage);}}});

let drag=null,suppressClick=false;
const canvas=$('pCanvas');canvas.setAttribute('tabindex','0');canvas.setAttribute('aria-label','project preview. arrow keys rotate; plus and minus zoom; home resets.');
canvas.addEventListener('pointerdown',e=>{if(view!=='model'||e.button!==0)return;drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,id:e.pointerId};suppressClick=false;canvas.setPointerCapture?.(e.pointerId);});
canvas.addEventListener('pointermove',e=>{if(!drag||e.pointerId!==drag.id)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)suppressClick=true;yaw+=dx*.45;pitch=Math.max(-80,Math.min(80,pitch+dy*.35));drag.x=e.clientX;drag.y=e.clientY;drawPreview();});
function stopDrag(){drag=null;}canvas.addEventListener('pointerup',stopDrag);canvas.addEventListener('pointercancel',stopDrag);canvas.addEventListener('lostpointercapture',stopDrag);
function zoomBy(delta){zoom=Math.max(.65,Math.min(2.5,zoom+delta));view='model';render();}
$('pZoomIn').onclick=()=>zoomBy(.15);$('pZoomOut').onclick=()=>zoomBy(-.15);$('pResetView').onclick=()=>{yaw=0;pitch=0;zoom=1;view='model';render();};
canvas.addEventListener('keydown',e=>{if(view!=='model')return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key)){e.preventDefault();if(e.key==='Home'){yaw=0;pitch=0;zoom=1;}else if(e.key==='+'||e.key==='=')zoom=Math.min(2.5,zoom+.15);else if(e.key==='-')zoom=Math.max(.65,zoom-.15);else if(e.key==='ArrowLeft')yaw-=15;else if(e.key==='ArrowRight')yaw+=15;else pitch=Math.max(-80,Math.min(80,pitch+(e.key==='ArrowUp'?-10:10)));drawPreview();}});
canvas.addEventListener('click',e=>{if(suppressClick){suppressClick=false;return;}if(view!=='model')return;const bead=e.target.closest('[data-pbead]');if(!bead)return;const c=g.components.find(c=>c.id===g.byId.get(bead.dataset.pbead).component);$('full-stage-'+c.stage)?.scrollIntoView?.({behavior:'smooth',block:'start'});});
$('pGraphExport').onclick=()=>T.download(JSON.stringify(g.constructionGraph,null,2),'application/json','-construction.json');
window.BeadPartsStudio={refresh,select,reveal,modelSVG,mapSVG,threadSVG,textGuide,printGuide,exports,get model(){return g;},get view(){return view;}};refresh();
})();
