(function(root){
'use strict';
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,k)=>a.map(v=>v*k),dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0),len=a=>Math.hypot(...a),unit=a=>mul(a,1/(len(a)||1)),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],mean=a=>mul(a.reduce(add,[0,0,0]),1/a.length),edge=(a,b)=>[a,b].sort((a,b)=>a-b).join(':');
const cache={};
function hull(v){const groups=new Map();for(let a=0;a<v.length;a++)for(let b=a+1;b<v.length;b++)for(let c=b+1;c<v.length;c++){const n=unit(cross(sub(v[b],v[a]),sub(v[c],v[a])));if(len(n)<.5)continue;const ds=v.map(p=>dot(n,sub(p,v[a])));if(ds.some(d=>d>1e-6)&&ds.some(d=>d< -1e-6))continue;const ids=ds.map((d,i)=>Math.abs(d)<1e-6?i:-1).filter(i=>i>=0);groups.set(ids.join(','),ids);}return [...groups.values()].map(ids=>{const center=mean(ids.map(i=>v[i])),n=unit(center),u=unit(sub(v[ids[0]],center)),w=cross(n,u);return ids.sort((a,b)=>Math.atan2(dot(sub(v[a],center),w),dot(sub(v[a],center),u))-Math.atan2(dot(sub(v[b],center),w),dot(sub(v[b],center),u)));});}
function angleBall(big=false){const name=big?'big':'small';if(cache[name])return cache[name];const p=(1+Math.sqrt(5))/2;let v=[];if(!big){for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])v.push([x,y,z]);for(const a of [-1,1])for(const b of [-1,1])v.push([0,a/p,b*p],[a/p,b*p,0],[b*p,0,a/p]);}else{const ico=[];for(const a of [-1,1])for(const b of [-1,1])ico.push([0,a,b*p],[a,b*p,0],[b*p,0,a]);for(let a=0;a<ico.length;a++)for(let b=0;b<ico.length;b++)if(Math.abs(len(sub(ico[a],ico[b]))-2)<1e-6)v.push(mul(add(mul(ico[a],2),ico[b]),1/3));}const f=hull(v);return cache[name]=normalize({v,f,kind:'ball'});}
function ball(big=false,profile="ball",economy=false){const P=root.BeadPeyote||(typeof require==='function'?require('./peyote-ball.js'):null);return P.ball(big,profile,economy);}
function normalize(mesh){const edges=new Map();for(const f of mesh.f)for(let j=0;j<f.length;j++)edges.set(edge(f[j],f[(j+1)%f.length]),[f[j],f[(j+1)%f.length]]);const mid=[...edges.values()].map(([a,b])=>mul(add(mesh.v[a],mesh.v[b]),.5));let d=Infinity;for(let a=0;a<mid.length;a++)for(let b=a+1;b<mid.length;b++)d=Math.min(d,len(sub(mid[a],mid[b])));const scale=2.05/d;mesh.v=mesh.v.map(p=>mul(p,scale));mesh.edges=[...edges.values()];mesh.radius=Math.max(...mesh.v.map(len));return mesh;}
function tube(segments=3){const v=[],f=[],n=5;for(let j=0;j<=segments;j++)for(let i=0;i<n;i++)v.push([Math.cos(i*2*Math.PI/n)*1.18,j-segments/2,Math.sin(i*2*Math.PI/n)*1.18]);f.push([4,3,2,1,0]);for(let j=0;j<segments;j++)for(let i=0;i<n;i++)f.push([j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i]);f.push(Array.from({length:n},(_,i)=>segments*n+i));return {...normalize({v,f,kind:'tube'}),segments};}
function panel(kind){
 let v,f;
 if(kind==='sheet'){v=Array.from({length:9},(_,i)=>[(i%3)-1,Math.floor(i/3)-1,0]);f=[[0,1,4,3],[1,2,5,4],[3,4,7,6],[4,5,8,7]];}
 else if(kind==='paw'){v=[[0,-1,0],[-1,0,0],[0,1,0],[1,0,0]];f=[[0,1,2,3]];}
 else if(kind==='fan'){v=[[-1.5,0,0],[-.5,0,0],[.5,0,0],[1.5,0,0],[-3,3,0],[-1,3.5,0],[1,3.5,0],[3,3,0]];f=[[0,1,5,4],[1,2,6,5],[2,3,7,6]];}
 else if(kind==='cone'){v=[[0,3,0],[-1.5,-1,1.5],[1.5,-1,1.5],[1.5,-1,-1.5],[-1.5,-1,-1.5]];f=[[1,2,0],[2,3,0],[3,4,0],[4,1,0],[4,3,2,1]];}
 else{v=[[0,-3,0],[-1.5,-1,0],[0,0,0],[1.5,-1,0],[-1.5,1,0],[0,3,0],[1.5,1,0]];f=[[0,1,2,3],[1,4,5,2],[2,5,6,3]];}
 const m=normalize({v,f,kind});m.open=kind!=='cone';return m;
}
function strand(count=5){const v=Array.from({length:count+1},(_,i)=>[0,(i-count/2)*1.5,0]);return {v,f:[],edges:Array.from({length:count},(_,i)=>[i,i+1]),radius:count*.75,kind:'strand',count};}
function eyeBead(){return {v:[[0,-2,0],[0,2,0]],edges:[[0,1]],f:[],radius:2,kind:'strand',count:1,eye:true,diameterMm:4};}
function example(shape){const p=(name,type,center,size,color,end=center,role='solid')=>({name,type,center,size,color,end,role});const body=p('body','ellipsoid',[0,0,0],[1,1,1],'#7caa80');const eye=(x,y,z)=>p(x<0?'left eye':'right eye','ellipsoid',[x,y,z],[.15,.15,.2],'#26382e',undefined,'paint');
if(['leaf','fan','cone','pear','dome'].includes(shape))return {title:shape+' practice part',parts:[p(shape==='cone'?'pointed tip':shape,'ellipsoid',[0,0,0],[1,1,1],'#a9c8a0')]};
if(shape==='butterfly')return {title:'meadow butterfly',parts:[p('body','ellipsoid',[0,0,0],[.4,.75,.35],'#7caa80'),...[-1,1].flatMap(x=>[p(x<0?'left upper wing':'right upper wing','capsule',[x*.25,.3,0],[.6,.7,.13],'#e69db4',[x*1.5,1.1,0]),p(x<0?'left lower wing':'right lower wing','capsule',[x*.25,-.15,0],[.5,.5,.13],'#d7b3ca',[x*1.3,-.8,0])]),...[-1,1].map(x=>p('antenna '+x,'capsule',[x*.15,.65,0],[.08,.08,.08],'#416444',[x*.5,1.3,0]))]};
if(shape==='turtle')return {title:'pond turtle',parts:[p('shell dome','ellipsoid',[0,0,0],[1,.6,1],'#679d71'),p('head','ellipsoid',[0,.15,1],[.4,.4,.4],'#a9c8a0'),...[-1,1].flatMap(x=>[-1,1].map(z=>p('flipper '+x+' '+z,'capsule',[x*.65,-.25,z*.45],[.3,.12,.25],'#a9c8a0',[x*1.3,-.3,z*.8]))),p('pointed tail','ellipsoid',[0,-.1,-1],[.2,.2,.4],'#7caa80'),eye(-.15,.3,1.35),eye(.15,.3,1.35)]};
if(shape==='bird')return {title:'little songbird',parts:[p('pear body','ellipsoid',[0,0,0],[.8,1,.65],'#e69db4'),p('head','ellipsoid',[0,.9,.25],[.5,.5,.5],'#d7b3ca'),p('beak','ellipsoid',[0,.95,.8],[.2,.2,.3],'#dfb85c'),...[-1,1].map(x=>p(x<0?'left wing':'right wing','capsule',[x*.55,.25,0],[.15,.45,.4],'#7caa80',[x*.85,-.55,0])),p('fan tail','capsule',[0,-.6,-.35],[.4,.2,.12],'#a9c8a0',[0,-1.3,-.7]),eye(-.25,1.05,.6),eye(.25,1.05,.6)]};
if(shape==='ball')return {title:'bead ball',parts:[body]};
if(shape==='heart')return {title:'two-lobed heart charm',parts:[p('left lobe','ellipsoid',[-.65,.45,0],[.7,.7,.7],'#d889a6'),p('right lobe','ellipsoid',[.65,.45,0],[.7,.7,.7],'#d889a6'),p('tapered tip','capsule',[0,0,0],[.45,.45,.45],'#d889a6',[0,-1,0])]};
if(shape==='fish')return {title:'little fish',parts:[{...body,color:'#e5a1b8'},p('tail stem','capsule',[-.7,0,0],[.3,.3,.3],'#7caa80',[-1.5,0,0]),p('upper tail','capsule',[-1.4,0,0],[.13,.13,.13],'#7caa80',[-2,.7,0]),p('lower tail','capsule',[-1.4,0,0],[.13,.13,.13],'#7caa80',[-2,-.7,0]),eye(.45,.25,.85)]};
if(shape==='bunny'||shape==='bear'){const bunny=shape==='bunny',c=bunny?'#f5e8dd':'#bd957d';return {title:bunny?'pocket bunny':'round bear',parts:[{...body,color:c},p('head','ellipsoid',[0,1.2,0],[.7,.7,.7],c),...[-1,1].map(x=>p(x<0?'left ear':'right ear',bunny?'capsule':'ellipsoid',[x*.45,1.8,0],[.27,.27,.27],c,[x*.55,bunny?2.8:1.8,0])),...[-1,1].map(x=>p(x<0?'left foot':'right foot','capsule',[x*.45,-.7,.3],[.3,.3,.3],c,[x*.6,-1.2,.5])),eye(-.28,1.35,.6),eye(.28,1.35,.6)]};}
const side=x=>x<0?'left':'right';
return {title:'garden frog',parts:[
 p('head and body','ellipsoid',[0,0,0],[1,1,1],'#a9c8a0'),
 ...[-1,1].map(x=>p(side(x)+' black eye bead','ellipsoid',[x*.52,.63,.72],[.2,.2,.2],'#171c16')),
 ...[-1,1].map(x=>p(side(x)+' back leg','capsule',[x*.65,-.45,.1],[.12,.12,.12],'#679d71',[x*.85,-.85,.38])),
 ...[-1,1].map(x=>p(side(x)+' front arm','capsule',[x*.8,-.24,.02],[.23,.23,.23],'#a9c8a0',[x*1.08,-.64,.1])),
 p('cream belly','ellipsoid',[0,-.12,.74],[.61,.56,.25],'#e6e8be',undefined,'paint'),
 p('smile','capsule',[-.25,.12,.94],[.08,.08,.08],'#416444',[.25,.12,.94],'paint')
]};}

function amigurumiScene(design){const scene=root.BeadShape.scene(design);return {...scene,parts:scene.parts.map(part=>{const p={...part,center:part.center.slice(),end:part.end.slice(),size:part.size.slice()};if(p.role==='solid'&&p.type==='capsule'&&/\b(arm|leg|shin|foot|paw)s?\b/i.test(p.name)){p.end=p.end.map((v,i)=>p.center[i]+(v-p.center[i])*.6);}return p;})};}
function parentFor(child,earlier){const name=child.source.name.toLowerCase(),side=/\bleft\b/.test(name)?'left':/\bright\b/.test(name)?'right':null;let candidates=earlier.filter(c=>c.kind!=='strand'&&(!side||!c.source.name.toLowerCase().includes(side==='left'?'right':'left')));if(!candidates.length)candidates=earlier.filter(c=>c.kind!=='strand');if(!candidates.length)candidates=earlier;
 const preferred=/\b(arm|leg|legs|foot|feet|paw|haunch|thigh|shin)\b/.test(name)?/body|torso|shell/:/raised eye/.test(name)?/head/:/\bhead\b/.test(name)?/neck/:/shin/.test(name)?/haunch|thigh/:/webbed foot|\bfoot\b|\bpaw\b/.test(name)?/shin|leg/:/arm|leg|haunch|thigh/.test(name)?/body|torso/:null;
 const matched=preferred?candidates.filter(c=>preferred.test(c.source.name.toLowerCase())&&(!side||!(/left|right/.test(c.source.name.toLowerCase()))||c.source.name.toLowerCase().includes(side))):[];if(matched.length)candidates=matched;
 return candidates.slice().sort((a,b)=>len(sub(a.source.center,child.source.center))-len(sub(b.source.center,child.source.center)))[0];}
function orient(p,axis){const y=unit(axis),x=unit(cross(y,Math.abs(y[2])<.9?[0,0,1]:[1,0,0])),z=cross(x,y);return add(add(mul(x,p[0]),mul(y,p[1])),mul(z,p[2]));}
function buildSeparate(design,{detail=3,threadDiameter=.25}={}){
 const economy=detail<4,scene=amigurumiScene(design),solids=scene.parts.filter(p=>p.role==='solid');if(!solids.length)throw Error('This design needs a solid body.');if(solids.length>18)throw Error('Simplify this subject to at most 18 main parts for the parts guide.');
 const g={structure:'modules',settings:{threadDiameter},nodes:[],byId:new Map(),faces:[],steps:[],stages:[],components:[],joins:[],palette:[],colors:[],passLimit:threadDiameter===.2?8:6,counts:new Map(),notes:[]};
 const base=solids.filter(p=>p.type!=='capsule').sort((a,b)=>Math.max(...b.size)-Math.max(...a.size))[0]||solids[0],scale=(/head.*body/i.test(base.name)?ball(true,'body'):ball(!economy)).radius/Math.max(...base.size),remaining=solids.slice();let section=0;
 function colorIndex(h){let i=g.palette.indexOf(h);if(i<0){i=g.palette.length;g.palette.push(h);}return i;}
 while(remaining.length){let source;if(!g.components.length)source=base;else source=remaining.slice().sort((a,b)=>Number(/neck/i.test(b.name))-Number(/neck/i.test(a.name))||(a.type==='capsule')-(b.type==='capsule')||Math.min(...g.components.map(c=>len(sub(a.center,c.source.center))))-Math.min(...g.components.map(c=>len(sub(b.center,c.source.center)))))[0];remaining.splice(remaining.indexOf(source),1);
  const id='P'+(g.components.length+1),axis=source.type==='capsule'?sub(source.end,source.center):[0,1,2].map(i=>i===source.size.indexOf(Math.max(...source.size))?1:0),length=source.type==='capsule'?len(axis):Math.max(...source.size)*2,thin=Math.min(...source.size)*scale<1.35||/whisker|antenna|toe|tendril/.test(source.name.toLowerCase()),elongated=source.type==='capsule'||Math.max(...source.size)/Math.min(...source.size)>2.2;
  const name=source.name.toLowerCase(),flat=Math.min(...source.size)<Math.max(...source.size)*.32;
  let mesh=/flat sheet/.test(name)?panel('sheet'):/practice tube/.test(name)?tube(2):/practice strand/.test(name)?strand(5):/black eye bead|large eye bead/.test(name)?eyeBead():/head.*body/.test(name)?ball(true,'body'):/\b(leg|legs|shin|haunch|thigh)\b/.test(name)?strand(4):/\b(arm|arms)\b/.test(name)?strand(3):/webbed foot|\bpaw\b/.test(name)?panel('paw'):/\bhead\b/.test(name)&&source!==base?ball(true):economy&&/ear/.test(name)&&Math.max(...source.size)/Math.max(...base.size)<.22?ball(false,'dome',true):/webbed|fan|fluke/.test(name)?panel('fan'):/beak|horn|spike|pointed/.test(name)?panel('cone'):/wing|\bfin(s)?\b|leaf|leaves|petal|flipper/.test(name)||(/ear/.test(name)&&elongated)||(flat&&source.type!=='capsule')?panel('leaf'):/raised eye|dome|shell|\bcap\b/.test(name)?ball(!economy&&source===base,'dome',economy&&source!==base):/haunch|\bpear\b|teardrop/.test(name)?ball(false,'pear',economy):economy&&/shin|neck|\bleg\b/.test(name)?tube(/neck/.test(name)?Math.max(1,Math.min(3,Math.round(length*scale/2.4))):1):elongated?(thin?strand(Math.max(3,Math.min(16,Math.round(length*scale/1.5)))):tube(Math.max(1,Math.min(8,Math.round(length*scale/2.4))))):ball(!economy&&Math.max(...source.size)/Math.max(...base.size)>.8);

  const center=source.type==='capsule'?mul(add(source.center,source.end),.5):source.center,world=mul(center,scale),vs=mesh.v.map(p=>add(world,mesh.stitch==='peyote'?p:orient(p,axis))),comp={id,name:source.name,kind:mesh.kind,source,mesh,world,vertices:vs,ids:[],stage:g.stages.length,parent:null};
  const edges=new Map();for(const [a,b]of mesh.edges){const nid='B'+String(g.nodes.length+1).padStart(4,'0'),local=mul(add(mesh.v[a],mesh.v[b]),.5),p=mul(add(vs[a],vs[b]),.5),n={id:nid,index:g.nodes.length,p,local,ends:[id+':'+a,id+':'+b],vertices:[a,b],axis:1,component:id,addedAt:-1,color:source.color,diameterMm:mesh.eye?4:2,material:mesh.eye?'4 mm black round eye bead':'11/0 round seed bead'};g.nodes.push(n);g.byId.set(nid,n);g.counts.set(nid,0);comp.ids.push(nid);edges.set(edge(a,b),nid);}
  const faces=mesh.f.map((f,i)=>({id:id+'F'+(i+1),corners:f.map(v=>id+':'+v),ids:f.map((v,j)=>edges.get(edge(v,f[(j+1)%f.length])))}));g.faces.push(...faces);const pending=faces.slice(),known=new Set(),future=new Map(comp.ids.map(id=>[id,faces.filter(f=>f.ids.includes(id)).length]));let current=null;const startIndex=g.steps.length;
  function route(from,to,allow){if(from===to)return [];if(from===null)return null;const q=[from],seen=new Map([[from,null]]);for(let i=0;i<q.length;i++)for(const id of known){if((allow.get(id)||0)<1)continue;const e=g.byId.get(id).ends;if(!e.includes(q[i]))continue;const next=e[0]===q[i]?e[1]:e[0];if(seen.has(next))continue;seen.set(next,{from:q[i],id});if(next===to){const out=[];let x=to;while(seen.get(x)){const n=seen.get(x);out.unshift(n.id);x=n.from;}return out;}q.push(next);}return null;}
  if(mesh.stitch==='peyote'){
   section++;let prev=null;const seen=new Set();for(const group of mesh.groups){const ids=[],moves=[];for(const i of group.sequence){const bead=comp.ids[i],n=g.byId.get(bead),kind=seen.has(bead)?'pass':'pick',o={id:bead,kind,from:n.ends[0],to:n.ends[1],phase:'weave',section,newThread:prev===null,bridge:prev!==null};moves.push(o);prev=o;if(kind==='pick'){ids.push(bead);n.addedAt=g.steps.length;}seen.add(bead);g.counts.set(bead,g.counts.get(bead)+1);}if(group.pauseBefore)moves[0].pauseBefore=group.pauseBefore;g.steps.push({index:g.steps.length,label:group.label,ids,ops:moves,moves,component:id});}
  }else if(mesh.kind==='strand'){
   const ids=comp.ids,ops=ids.map(id=>({kind:'pick',id})).concat(ids.slice(0,-1).reverse().map((id,i)=>({kind:'pass',id,bridge:i===0,reverse:true})));section++;const moves=[];for(let i=0;i<ops.length;i++){const o=ops[i],n=g.byId.get(o.id),from=n.ends[o.reverse?1:0],to=n.ends[o.reverse?0:1];moves.push({...o,from,to,phase:'weave',newThread:i===0,section});g.counts.set(o.id,g.counts.get(o.id)+1);if(o.kind==='pick')n.addedAt=g.steps.length;}
   g.steps.push({index:g.steps.length,label:mesh.eye?'pick up the 4 mm black eye bead':'string, skip the tip, and return',ids:ids.slice(),ops,moves,component:id});
  }else while(pending.length){
   let best=null;for(const f of pending){if(known.size&&!f.ids.some(id=>known.has(id)))continue;for(let start=0;start<f.ids.length;start++)for(const reverse of [false,true]){const corners=reverse?f.corners.slice().reverse():f.corners,ordered=corners.map((_,j)=>corners[(j+start)%corners.length]),ring=ordered.map((v,j)=>f.ids.find(id=>{const e=g.byId.get(id).ends;return e.includes(v)&&e.includes(ordered[(j+1)%ordered.length]);}));if(known.size&&!known.has(ring[0]))continue;
     const seq=[...ring,ring[0]],needed=new Map();seq.forEach(id=>needed.set(id,(needed.get(id)||0)+1));const allowance=new Map(comp.ids.map(id=>[id,g.passLimit-g.counts.get(id)-(needed.get(id)||0)-(future.get(id)-(f.ids.includes(id)?1:0))]));if([...allowance.values()].some(n=>n<0))continue;
     let travel=route(current,ordered[0],allowance),restart=travel===null;if(restart)travel=[];const score=(restart&&known.size?100:0)+travel.length*3+seq.reduce((n,id)=>n+g.counts.get(id),0)-f.ids.filter(id=>known.has(id)).length;
     if(!best||score<best.score)best={f,ring,seq,ordered,travel,restart,score};
   }}if(!best)throw Error('This part needs more hole space than the planned passage limit. Try 0.20 mm line or a smaller design.');
   const {f,seq,travel,ordered,restart}=best;if(restart||current===null){section++;current=ordered[0];}const moves=[],ids=[],ops=[];
   for(const bead of [...travel,...seq]){const n=g.byId.get(bead),position=moves.length<travel.length,kind=known.has(bead)?'pass':'pick',from=current,to=n.ends[0]===from?n.ends[1]:n.ends[0];if(!n.ends.includes(from))throw Error('Disconnected part route.');const move={id:bead,kind,from,to,phase:position?'position':'weave',section,newThread:moves.length===0&&(restart||g.steps.length===startIndex)};moves.push(move);ops.push({id:bead,kind});if(kind==='pick'){ids.push(bead);n.addedAt=g.steps.length;}known.add(bead);g.counts.set(bead,g.counts.get(bead)+1);current=to;}
   f.ids.forEach(id=>future.set(id,future.get(id)-1));g.steps.push({index:g.steps.length,label:`close ${f.ids.length}-bead loop ${faces.indexOf(f)+1}`,ids,ops,moves,component:id,faceId:f.id});pending.splice(pending.indexOf(f),1);
  }
  g.components.push(comp);makeStage(comp,g.steps.slice(startIndex));
 }
 function makeStage(comp,steps){const operations=steps.flatMap(st=>st.moves.map((o,i)=>({...o,step:st.index,local:i,cube:comp.id}))),ids=steps.flatMap(st=>st.ids),kind=comp.kind;const caption=comp.mesh.eye?'1 bead · 4 mm black round eye · through-hole attachment':comp.mesh.stitch==='peyote'?`${ids.length} beads · ${kind} · shaped circular peyote`:kind==='tube'?`${ids.length} beads · five-sided tube · ${comp.mesh.segments} wall repeats`:`${ids.length} beads · ${['leaf','fan','cone','paw','sheet'].includes(kind)?kind+' · angle weave':'flexible strand · skip the tip on the return'}`;
  const st={index:g.stages.length,label:'make '+comp.name,caption,kind,component:comp.id,start:steps[0].index,end:steps.at(-1).index,steps,blocks:[{cubeId:comp.id,steps}],ids,nodeIds:comp.ids.slice(),operations,parts:[comp.name]};g.stages.push(st);comp.stage=st.index;st.layout=layout(g,comp);st.instruction=comp.mesh.eye?'Pick up one 4 mm black round bead through its hole. Seat it close to the marked body anchor; the next join step reinforces it. This eye is one bead, not a seed-bead ball.':comp.mesh.stitch==='peyote'?`String five foundation beads and circle through the first. Work between the previous round’s up-beads: add one normally, two at each marked increase; at a decrease add one then pass through the two listed up-beads. Step up through the first new bead at each round end. ${comp.mesh.open?'Leave the last round open as the dome rim; attach the crown anchor in the next step.':'Draw the final five up-beads together.'} ${comp.mesh.open?'':'Optional filling: pause before the first decrease and lightly fill the hollow form with clean soft plastic film or craft filling. Keep the rim and bead holes clear; then decrease and close.'} The chart shows the whole surface; use the exact sequence for shaping and step-ups. This shaped peyote form is a draft: check the cup shape and tension with your beads before continuing.`:['leaf','fan','cone','paw','sheet'].includes(kind)?`Work the ${kind==='cone'?'triangular side loops and square base':'adjoining four-bead angle-weave loops'} in the listed order, reusing shared beads. ${kind==='cone'?'The sides meet in a pointed cap.':kind==='sheet'?'Keep these four adjoining loops flat; shared edges reuse the same beads.':kind==='paw'?'Keep this single four-bead loop snug as a tiny rounded paw. Do not spread it into a fan.':kind==='fan'?'Spread the three panels into a fan; its wide edge makes the webbed foot or tail.':'Keep this pointed panel flat or gently cupped for a leaf, wing or fin.'} This is a whole-part diagram; follow the arrows and exact passes.`:kind==='tube'?`Start with a five-bead end ring. Work the four-bead wall loops around it and repeat along the tube. Close the other end. The nested pentagons show the whole tube wall at once, viewed through one end.`:`String the ${ids.length} beads. Skip the final tip bead, then pass back through the other ${ids.length-1} beads. Keep both tails at the base for attachment. This part stays flexible on fishing line.`;
 }
 for(let ci=1;ci<g.components.length;ci++){
  const child=g.components[ci],parent=parentFor(child,g.components.slice(0,ci));child.parent=parent.id;
  const limb=/\b(arm|arms|leg|legs|foot|feet|paw|haunch|thigh|shin)\b/i.test(child.name);if(limb){const side=/left/i.test(child.name)?-1:/right/i.test(child.name)?1:Math.sign(child.source.center[0]-parent.source.center[0]);child.allowedParentIds=parent.ids.filter(id=>{const n=g.byId.get(id),q=sub(n.p,parent.world);return q[1]<-.15*parent.mesh.radius&&(!side||q[0]*side>parent.mesh.radius*.25)&&q[2]<parent.mesh.radius*.45;});if(!child.allowedParentIds.length)throw Error('No lower-body anchor is available for '+child.name+'. Adjust the body shape.');}

  let direction=unit(sub(child.world,mul(parent.source.type==='capsule'?mul(add(parent.source.center,parent.source.end),.5):parent.source.center,scale)));if(len(direction)<.1)direction=[0,1,0];if(child.mesh.stitch==='peyote'){const axis=mul(direction,-1);child.vertices=child.mesh.v.map(v=>add(child.world,orient(v,axis)));for(const id of child.ids){const n=g.byId.get(id);n.local=orient(n.local,axis);n.p=add(child.world,n.local);}}const extent=Math.max(...parent.ids.map(id=>dot(sub(g.byId.get(id).p,parent.world),direction)))-Math.min(...child.ids.map(id=>dot(sub(g.byId.get(id).p,child.world),direction)))+(child.mesh.eye?3.1:2.1);let delta=sub(add(parent.world,mul(direction,extent)),child.world);
  for(let attempt=0;attempt<20;attempt++){const collision=g.components.slice(0,ci).some(c=>c.ids.some(a=>child.ids.some(b=>len(sub(g.byId.get(a).p,add(g.byId.get(b).p,delta)))<((g.byId.get(a).diameterMm||2)+(g.byId.get(b).diameterMm||2))/2+.02)));if(!collision)break;delta=add(delta,mul(direction,.5));}
  if(child.kind==='strand'){
   const axis=unit(sub(child.source.end,child.source.center)),first=g.byId.get(child.ids[0]),candidates=parent.ids.filter(id=>(!child.allowedParentIds||child.allowedParentIds.includes(id))&&g.counts.get(id)+2<=g.passLimit).map(id=>{const n=g.byId.get(id),shift=sub(add(n.p,mul(axis,child.mesh.eye?3.2:2.2)),first.p);const collisions=g.components.slice(0,ci).reduce((sum,c)=>sum+c.ids.reduce((sum,a)=>sum+child.ids.filter(b=>len(sub(g.byId.get(a).p,add(g.byId.get(b).p,shift)))<((g.byId.get(a).diameterMm||2)+(g.byId.get(b).diameterMm||2))/2+.02).length,0),0);return {shift,score:collisions*1000+len(sub(add(child.world,shift),add(parent.world,mul(direction,extent))))};}).sort((a,b)=>a.score-b.score);if(candidates.length)delta=candidates[0].shift;
  }
  child.world=add(child.world,delta);child.vertices=child.vertices.map(v=>add(v,delta));child.ids.forEach(id=>{const n=g.byId.get(id);n.p=add(n.p,delta);});
  const pairs=[];const used=new Set();for(let j=0;j<(child.kind==='strand'?1:2);j++){const candidates=[];for(const a of parent.ids)for(const b of child.ids)if((!child.allowedParentIds||child.allowedParentIds.includes(a))&&!used.has(a)&&!used.has(b)&&g.counts.get(a)+2<=g.passLimit&&g.counts.get(b)+2<=g.passLimit)candidates.push({a,b,d:len(sub(g.byId.get(a).p,g.byId.get(b).p))});candidates.sort((a,b)=>a.d-b.d);if(!candidates.length)throw Error('There is not enough reserved hole space for this join. Simplify the parts or use 0.20 mm line.');const pair=candidates[0];pairs.push(pair);used.add(pair.a);used.add(pair.b);}
  const moves=[];for(const pair of pairs){section++;for(const [i,id]of [pair.a,pair.b,pair.a,pair.b].entries()){const n=g.byId.get(id);moves.push({id,kind:'pass',from:n.ends[0],to:n.ends[1],phase:'weave',section,newThread:i===0,bridge:i>0});g.counts.set(id,g.counts.get(id)+1);}}
  const step={index:g.steps.length,label:'join '+child.name+' to '+parent.name,ids:[],ops:moves,moves,component:child.id};g.steps.push(step);const operations=moves.map((o,i)=>({...o,step:step.index,local:i,cube:child.id})),st={index:g.stages.length,label:step.label,caption:`No new beads · ${pairs.length} attachment loop${pairs.length===1?'':'s'} · green anchors are on ${parent.name}`,kind:'join',component:child.id,parent:parent.id,start:step.index,end:step.index,steps:[step],blocks:[{cubeId:child.id,steps:[step]}],ids:[],nodeIds:[...used],operations,parts:[child.name,parent.name],pairs,instruction:`Make both parts first. Bring the labelled anchor beads together. For each pair, secure a fresh working length beside the parent anchor; pass parent → child → parent → child, then secure the ends. ${pairs.length===2?'Use both pairs to reduce twisting.':'This is a flexible attachment.'} Finishing passes are additional; check the actual hole space.`};st.layout=joinLayout(g,st);g.stages.push(st);g.joins.push(st);
 }
 // Colour markings are painted onto these beads, never built as floating parts.
 for(const comp of g.components){const r=Math.max(...comp.mesh.v.map(len));for(const id of comp.ids){const n=g.byId.get(id),sample=add(comp.source.center,n.local.map((v,i)=>v/r*comp.source.size[i]));for(const paint of scene.parts.filter(p=>p.role==='paint'))if(root.BeadShape.contains(paint,sample))n.color=paint.color;}}
 for(const paint of scene.parts.filter(p=>p.role==='paint')){const comp=g.components.slice().sort((a,b)=>len(sub(a.source.center,paint.center))-len(sub(b.source.center,paint.center)))[0],ids=comp.ids.filter(id=>!g.byId.get(id).landmark);if(ids.length){const r=Math.max(...comp.mesh.v.map(len)),n=ids.map(id=>g.byId.get(id)).sort((a,b)=>len(sub(add(comp.source.center,a.local.map((v,i)=>v/r*comp.source.size[i])),paint.center))-len(sub(add(comp.source.center,b.local.map((v,i)=>v/r*comp.source.size[i])),paint.center)))[0];n.color=paint.color;n.landmark=true;}}
 g.materials=[...new Set(g.nodes.map(n=>n.material))].map(name=>({name,count:g.nodes.filter(n=>n.material===name).length}));for(const n of g.nodes)g.colors.push(colorIndex(n.color));g.maxPasses=Math.max(...g.counts.values());g.threadSections=section;g.title=scene.title;g.notes.push('Shaped parts simplify the subject. Balls, pears and open domes use circular peyote with explicit increases, decreases and step-ups; leaf and fan panels use adjoining four-bead angle-weave loops, points use triangular loops, and tubes use four-bead walls and five-bead ends. Amigurumi proportions use a generous head and short limbs while retaining defining ears, wings and necks. These are approximate forms; flat panels and open domes need a physical tension check.');if(scene.parts.some(p=>p.role==='cut'))g.notes.push('Cut-out regions are omitted in this simplified parts version. Review openings in the preview.');g.validation=validate(g);if(!g.validation.valid)throw Error(g.validation.errors.join(' '));return g;
}
function layout(g,c){if(['leaf','fan','cone','paw','sheet'].includes(c.kind)){const pv=c.kind==='cone'?[[0,0],[-150,150],[150,150],[150,-150],[-150,-150]]:c.mesh.v.map(p=>[p[0]*34,-p[1]*34+p[2]*12]),nodes=c.ids.map(id=>g.byId.get(id)),pos=nodes.map(n=>({x:(pv[n.vertices[0]][0]+pv[n.vertices[1]][0])/2,y:(pv[n.vertices[0]][1]+pv[n.vertices[1]][1])/2})),axes=nodes.map(n=>{const a=pv[n.vertices[0]],b=pv[n.vertices[1]],dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy)||1;return [dx/l,dy/l];});return boxLayout(nodes,pos,axes);}if(c.mesh.stitch==='peyote'){const nodes=c.ids.map(id=>g.byId.get(id)),pos=[],axes=[],roundForId=new Map(),radii=c.mesh.rounds.map((_,r)=>52+r*43),outer=radii.at(-1),W=Math.max(560,outer*2+150),H=W,cx=W/2,cy=H/2;for(let r=0;r<c.mesh.rounds.length;r++){const row=c.mesh.rounds[r],rad=radii[r];row.forEach((i,j)=>{const a=c.mesh.angles[r][j]-Math.PI/2;pos[i]={x:cx+rad*Math.cos(a),y:cy+rad*Math.sin(a)};axes[i]=[-Math.sin(a),Math.cos(a)];roundForId.set(c.ids[i],r);});}return {nodes,index:new Map(nodes.map((n,i)=>[n.id,i])),pos,axes,W,H,roundForId,radii,roundCenter:{x:cx,y:cy},peyote:true};}let pv;if(c.kind==='strand')pv=c.mesh.v.map((p,i)=>[70+i*48,120,0]);else if(c.kind==='tube'){pv=c.mesh.v.map((p,i)=>{const ring=Math.floor(i/5),theta=i%5*2*Math.PI/5-Math.PI/2,r=65*(c.mesh.segments+1-ring);return [r*Math.cos(theta),r*Math.sin(theta),0];});}else{const f=c.mesh.f[0],normal=unit(mean(f.map(i=>c.mesh.v[i]))),u=unit(sub(c.mesh.v[f[0]],mean(f.map(i=>c.mesh.v[i])))),w=cross(normal,u),d=dot(c.mesh.v[f[0]],normal)+c.mesh.radius*.08;pv=c.mesh.v.map(p=>[dot(p,u)/(d-dot(p,normal)),dot(p,w)/(d-dot(p,normal)),0]);const outer=Math.max(...pv.map(len));pv=pv.map(p=>{const r=len(p);return r>1e-9?mul(p,300*Math.pow(r/outer,.38)/r):p;});}
 const nodes=c.ids.map(id=>g.byId.get(id)),pos=nodes.map(n=>{const p=mul(add(pv[n.vertices[0]],pv[n.vertices[1]]),.5);return {x:p[0],y:p[1]};}),axes=nodes.map(n=>{const p=sub(pv[n.vertices[1]],pv[n.vertices[0]]),d=Math.hypot(p[0],p[1])||1;return [p[0]/d,p[1]/d];});let mind=Infinity;for(let a=0;a<pos.length;a++)for(let b=a+1;b<pos.length;b++)mind=Math.min(mind,Math.hypot(pos[a].x-pos[b].x,pos[a].y-pos[b].y));const span=Math.max(Math.max(...pos.map(p=>p.x))-Math.min(...pos.map(p=>p.x)),Math.max(...pos.map(p=>p.y))-Math.min(...pos.map(p=>p.y)));const scale=c.kind==='ball'?Math.min(38/mind,820/span):1;pos.forEach(p=>{p.x*=scale;p.y*=scale;});return boxLayout(nodes,pos,axes);
}
function boxLayout(nodes,pos,axes){const minX=Math.min(...pos.map(p=>p.x)),minY=Math.min(...pos.map(p=>p.y)),dx=Math.max(...pos.map(p=>p.x))-minX,dy=Math.max(...pos.map(p=>p.y))-minY,W=Math.max(560,dx+130),H=Math.max(350,dy+130);pos.forEach(p=>{p.x+=(W-dx)/2-minX;p.y+=(H-dy)/2-minY;});return {nodes,index:new Map(nodes.map((n,i)=>[n.id,i])),pos,axes,W,H};}
function joinLayout(g,st){const nodes=st.pairs.flatMap(p=>[g.byId.get(p.a),g.byId.get(p.b)]),pos=nodes.map((n,i)=>({x:(i%2)*180,y:Math.floor(i/2)*120})),axes=nodes.map(()=>[0,1]);return boxLayout(nodes,pos,axes);}
function validate(g){const errors=[],added=g.stages.flatMap(s=>s.ids);if(added.length!==g.nodes.length||new Set(added).size!==g.nodes.length)errors.push('Each physical bead must be added exactly once.');if(g.maxPasses>g.passLimit)errors.push('Passage limit exceeded.');if(g.joins.length!==g.components.length-1)errors.push('Every part needs a joining plan.');for(const st of g.stages){let prev=null;for(const o of st.operations){const n=g.byId.get(o.id);if(!n||!n.ends.includes(o.from)||!n.ends.includes(o.to)||o.from===o.to)errors.push('Invalid bead-hole traversal.');if(prev&&!o.newThread&&!o.bridge&&prev.to!==o.from)errors.push('Disconnected working thread.');prev=o;}}if(g.continuous){let prev=null;for(const st of g.stages)for(const o of st.operations){if(prev&&!o.newThread){const a=g.byId.get(prev.id),b=g.byId.get(o.id);if(a.component!==b.component){const ca=g.components.find(c=>c.id===a.component),cb=g.components.find(c=>c.id===b.component);if(ca.parent!==cb.id&&cb.parent!==ca.id)errors.push('Thread must return through the parent beadwork before moving to another limb.');}}prev=o;}for(const join of g.joins)for(const pair of join.pairs)if(len(sub(g.byId.get(pair.a).p,g.byId.get(pair.b).p))>3.80001)errors.push('An attachment would leave a long exposed thread span.');}return {valid:!errors.length,errors};}
function build(design,options={}){const g=buildSeparate(design,options);if(options.continuous===false)return g;const C=root.BeadContinuous||(typeof require==='function'?require('./continuous-thread.js'):null);if(!C)throw Error('The continuous-thread planner is missing.');const planned=C.plan(g),G=root.BeadConstruction||(typeof require==='function'?require('./construction-graph.js'):null);return G?G.compile(planned):planned;}
root.BeadParts={build,example,ball,tube,strand,panel,amigurumiScene,validate};if(typeof module!=='undefined')module.exports=root.BeadParts;
})(typeof window!=='undefined'?window:globalThis);
