(() => {
'use strict';
const sources=[
 {title:'encyclopedia of needlework',creator:'thérèse de dillmont · digitized by project gutenberg volunteers',url:'https://www.gutenberg.org/ebooks/20776',read:'https://www.gutenberg.org/cache/epub/20776/pg20776-images.html',rights:'public domain in the usa, according to project gutenberg',note:'historical techniques, including knitting with beads. figures 534–536 illustrate intermediate and finished states. a teaching reference, not a tested 3d seed-bead animal pattern.',use:'informs our before/after teaching approach; no patterns or illustrations copied.'},
 {title:'barbour’s new bead book',creator:'national trading company, 1924 · scan donated by mary lou davis · antique pattern library',url:'https://www.antiquepatternlibrary.org/pub/PDF/BarbourNewBead.pdf',read:'https://www.antiquepatternlibrary.org/pub/PDF/BarbourNewBead.pdf',rights:'original described as public domain; edited scan: cc by-nc-sa 2.5',license:'https://creativecommons.org/licenses/by-nc-sa/2.5/',note:'historic bead patterns, including loom work. the scan has separate reuse conditions.',use:'reading link only. not copied into the app or a training dataset.'},
 {title:'peyote stitch — basics and beyond',creator:'melinda barta · interweave, 2010',url:'https://www.interweave.com/wp-content/uploads/peyote-basics-beyond-barta-illustrations.pdf',read:'https://www.interweave.com/wp-content/uploads/peyote-basics-beyond-barta-illustrations.pdf',rights:'free to read; copyrighted, not an open pattern collection',note:'flat, circular and tubular peyote technique diagrams. included as an optional learning link, not reusable source material.',use:'reading link only. no charts or text imported.'}
];
const esc=Beadform.ui.esc;
document.getElementById('patternSourcesButton').onclick=()=>Beadform.ui.modal('learn from the makers.',`<p class="modal-copy">credited references for learning. free to read does not always mean free to reuse.</p><div class="source-cards">${sources.map(s=>`<article class="source-card"><h3><a href="${s.read}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a></h3><p>${esc(s.creator)}</p><small>${esc(s.rights)}${s.license?` · <a href="${s.license}" target="_blank" rel="noopener noreferrer">license</a>`:''}</small><p>${esc(s.note)}</p><details><summary>how beadform uses this</summary><p>${esc(s.use)}</p><a href="${s.url}" target="_blank" rel="noopener noreferrer">source + credits ↗</a></details></article>`).join('')}</div><p class="help-text">reviewed september 20, 2026. these links open external sites. no downloaded patterns, remote images or training corpus are included.</p>`);
window.BeadPatternSources=sources;
})();
